### ISSUE TITLE
arbo: while down, could not get value for key

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#1100]
i came across this 
https://github.com/vocdoni/vocdoni-node/actions/runs/6144507814/job/16670040855?pr=1085
```
2023-09-11T09:26:59.389Z FTL end2endtest/main.go:160 > error waiting for election publish final results API error: 500 ({"error":"cannot fetch election: (c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000): while down, could not get value for key 1b61b629dfa8b08b5b0bd07571a40878a029ec4d0895ff79147419c62fcff412: key not found","code":5008}
```

and another error, possibly the same
https://github.com/vocdoni/vocdoni-node/actions/runs/6148876892/job/16683564829?pr=1085
```
2023-09-11T16:04:32.251Z DBG apiclient/client.go:160 > http request body=null path=/v2/chain/info type=GET
2023-09-11T16:04:32.252Z FTL end2endtest/main.go:145 > API error: 500 (while down, could not get value for key 1c6fd6193c90efff9322b0acb5821d9ba3007dba29221316b331dcb2cc5d2c51: key not found
```

**Comment by p4u** [comment]
The issue could be a data race.

Since the Arbo merkle tree is now deleting old nodes and making some internal re-structurations on every modification (to remove orphan nodes and to keep the tree as shorter as possible), a call might be performed on a tree that is being modified; thus the path ends in a node which children do not exist anymore.

This should not happen since we use mutex locks, but there might be some corner case.

**Comment by altergui** [comment]
so i'm digging into the first ocurrence.

some notes:
it was waiting for results, the previous queries (at 09:26:51 , 09:26:55) were ok (404)
and the one at 09:26:59.389 failed

```
2023-09-11T09:26:51.386Z DBG apiclient/client.go:160 > http request body=null path=/v2/elections/c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000/scrutiny type=GET
2023-09-11T09:26:55.387Z DBG apiclient/client.go:160 > http request body=null path=/v2/elections/c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000/scrutiny type=GET
2023-09-11T09:26:59.389Z DBG apiclient/client.go:160 > http request body=null path=/v2/elections/c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000/scrutiny type=GET
2023-09-11T09:26:59.389Z FTL end2endtest/main.go:160 > error waiting for election publish final results API error: 500 ({"error":"cannot fetch election: (c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000): while down, could not get value for key 1b61b629dfa8b08b5b0bd07571a40878a029ec4d0895ff79147419c62fcff412: key not found","code":5008}
```

here are some interesting things that happen around that time (09:26:59.3xx)
namely:
* at 09:26:59.370 a new block started being commited, IST computed results, and 20ms later...
* at 09:26:59.390 it was reported as commited

the arbo "key not found" happened exactly on this timeframe, so it looks like a race involving IST


```
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.347Z INF comet: finalizing commit of block hash={} num_txs=7 root=4BEC4798B65279EAC481EE33D94D98F5CE61E341C9DD1F1CFF62703F0020A181
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.37Z ERR vochain/app.go:364 > rejected tx error="voteTx: vote 5e5dbdad14bf9a9f22b8521bd6a122859e743dcfbab7257e0ebd7219202dd648 overwrite count reached"
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.37Z WRN vochain/app.go:299 > deliverTx failed code=1 data="voteTx: vote 5e5dbdad14bf9a9f22b8521bd6a122859e743dcfbab7257e0ebd7219202dd648 overwrite count reached" info= log=
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.371Z INF state/process.go:39 > new election censusOrigin=OFF_CHAIN_TREE_WEIGHTED censusRoot=4d8c49485d4966c06b2f40461c9b6469a916aefc01c7e402ed27a4aa91bc5c56 censusURI=ipfs://bafybeidsurfab4udztfik2kcdhbz6fu6phqsnhma4elzakkhxpihpjauiy endBlock=222 entityId=548be0e590ecb3d6563ad799acec0964bb583a1f envelopeType={} height=12 maxCensusSize=10 mode={"autoStart":true,"dynamicCensus":true,"interruptible":true} processId=c5d2460186f7548be0e590ecb3d6563ad799acec0964bb583a1f020000000000 startBlock=13 status=1 voteOptions={"costExponent":1,"maxCount":1,"maxTotalCost":2,"maxValue":2}
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.372Z INF results/compute.go:78 > computed results elapsed="136.151µs" process=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000 results=[90,0,0]
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.372Z INF ist/results.go:20 > committing results electionID=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.372Z INF comet: finalized block block_app_hash=1B61B629DFA8B08B5B0BD07571A40878A029EC4D0895FF79147419C62FCFF412 height=12 num_txs_res=7 num_val_updates=0
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.372Z INF comet: executed block app_hash="\x1ba�)ߨ��[\v�uq�\bx�)�M\b��y\x14t\x19�/��\x12" height=12
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.39Z INF vochain/app.go:340 > commit block height=12 txs=7
testsuite_6144507814-seed-1        | 2023-09-11T09:26:59.39Z INF comet: committed state block_app_hash=4BEC4798B65279EAC481EE33D94D98F5CE61E341C9DD1F1CFF62703F0020A181 height=12

testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.368Z DBG vochain/app.go:355 > deliver tx hash=bae9efc5f10fd404a9068133e7a9ce42c80b494f3a5820c22ce7ab692ea8366c height=12 tx={"Payload":{"SetProcess":{"nonce":1,"processId":"xdJGAYb3MoKZrfhuKAzXI5Vk6mgakqxFhioCCAAAAAA=","status":2,"txtype":2}}} type=setProcess
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.37Z DBG ist/ist.go:124 > schedule IST action action=commit-results height=13 id=c5d2460186f7328299adf86e280cd7239564ea681a92ac45862a020800000000
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.371Z DBG state/account.go:258 > burning fee for tx SET_PROCESS_STATUS with cost 1 from account 0x328299aDf86E280cD7239564Ea681A92ac45862a
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.371Z DBG state/account.go:202 > setAccount: address 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF, nonce 0, infoURI , balance: 155, delegates: [], processIndex: 0
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.371Z DBG state/account.go:202 > setAccount: address 0x328299aDf86E280cD7239564Ea681A92ac45862a, nonce 2, infoURI ipfs://bafybeifjedyxod63bkgdhvkse6qsy5mbt4643xtnxpmikbh74nixfuuvrq, balance: 99989, delegates: [], processIndex: 1
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.371Z DBG vochain/app.go:355 > deliver tx hash=63e05358e512b4423e03ffa478963cf86b552ef9ba73e634ac983e22896e7c44 height=12 tx={"Payload":{"Vote":{"nonce":"w+JP5KA412YP2CZGWMQiDdhV1cdhhN90KQ76IEA5Ye0=","processId":"xdJGAYb3gVR+Y90pg5V3q2zmjOVfgjImI8UCAAAAAAA=","proof":{"Payload":{"Arbo":{"availableWeight":"CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","keyType":1,"siblings":"RQABAAOp8rKV9IV2n9VpicWpfk45f+4ni9c/dPKILaUGgKEc2S3tuHqllb6jsxVotZOh6nvP0Sus/rvl0ng+sDXGeOsA"}}},"votePackage":"eyJ2b3RlcyI6WzRdfQ=="}}} type=vote
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.371Z DBG vochain/app.go:355 > deliver tx hash=97a1605295b0e873098e7f9e62076691d010c26b512c7762b33340c9a222acd7 height=12 tx={"Payload":{"Vote":{"nonce":"QtliCcUJ4jlVNZlxmQ4tmdBL/1/7CpRKTmquiRaYYAI=","processId":"xdJGAYb3gVR+Y90pg5V3q2zmjOVfgjImI8UCAAAAAAA=","proof":{"Payload":{"Arbo":{"availableWeight":"CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","keyType":1,"siblings":"RQABAAOp8rKV9IV2n9VpicWpfk45f+4ni9c/dPKILaUGgKEc2S3tuHqllb6jsxVotZOh6nvP0Sus/rvl0ng+sDXGeOsA"}}},"votePackage":"eyJ2b3RlcyI6WzVdfQ=="}}} type=vote
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.372Z DBG vochain/app.go:355 > deliver tx hash=af896a87d6611672ae13c5785dad29a331b518d74413de734b6ec138672e26f1 height=12 tx={"Payload":{"Vote":{"nonce":"kECcpgl2RskgDVcQ1RnWtArgnwjmLnZsWfchDl1O6WQ=","processId":"xdJGAYb3gVR+Y90pg5V3q2zmjOVfgjImI8UCAAAAAAA=","proof":{"Payload":{"Arbo":{"availableWeight":"CgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=","keyType":1,"siblings":"RQABAAOp8rKV9IV2n9VpicWpfk45f+4ni9c/dPKILaUGgKEc2S3tuHqllb6jsxVotZOh6nvP0Sus/rvl0ng+sDXGeOsA"}}},"votePackage":"eyJ2b3RlcyI6WzZdfQ=="}}} type=vote
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.372Z ERR vochain/app.go:364 > rejected tx error="voteTx: vote 5e5dbdad14bf9a9f22b8521bd6a122859e743dcfbab7257e0ebd7219202dd648 overwrite count reached"
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.372Z WRN vochain/app.go:299 > deliverTx failed code=1 data="voteTx: vote 5e5dbdad14bf9a9f22b8521bd6a122859e743dcfbab7257e0ebd7219202dd648 overwrite count reached" info= log=
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.372Z DBG vochain/app.go:355 > deliver tx hash=987c60aa44219fb24324b85d710b91beaa9667e950dd7fb98a77b6891e9b6ad6 height=12 tx={"Payload":{"SetProcess":{"nonce":1,"processId":"xdJGAYb3gVR+Y90pg5V3q2zmjOVfgjImI8UCAAAAAAA=","status":2,"txtype":2}}} type=setProcess
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.374Z DBG ist/ist.go:124 > schedule IST action action=commit-results height=13 id=c5d2460186f781547e63dd29839577ab6ce68ce55f82322623c5020000000000
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.374Z DBG state/account.go:258 > burning fee for tx SET_PROCESS_STATUS with cost 1 from account 0x81547E63dD29839577ab6CE68ce55f82322623C5
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.374Z DBG state/account.go:202 > setAccount: address 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF, nonce 0, infoURI , balance: 156, delegates: [], processIndex: 0
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.374Z DBG state/account.go:202 > setAccount: address 0x81547E63dD29839577ab6CE68ce55f82322623C5, nonce 2, infoURI ipfs://bafybeidvdgoyld3delvjdtlo2eftjh5hysigjyschm4vneyneopluxwuiy, balance: 99989, delegates: [], processIndex: 1
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.374Z DBG vochain/app.go:355 > deliver tx hash=2631fb0cbd978fa8d9dbce24dacd87407c1f021eaaac850549041179faa21c7f height=12 tx={"Payload":{"Vote":{"nonce":"Woy2XRObW8EcvgSfSPMxX5eCOXKHLtuXFbdZQ8J83LY=","nullifier":"LUciPGqq1ut3psA+hv+C3WLxQFJsbyWyTnl8Kb7Zzq0=","processId":"xdJGAYb3hBycAhCoFbiC4UkS5sVEHr1KqnMCAgAAAAA=","proof":{"Payload":{"ZkSnark":{"a":["15653270020116023178539615390561304115427464882527447527212330521503757447629","126838855467045305351974632720283395523353201076382435693452199339777254717","1"],"b":["20251121392022675811231465012037901442333282211358296714005480136372084559109","15501801999227380763879559818010543095809520470585457512461579868900122474652","12938182773923154732351332373734369116853461500370035817482812058789406107965","20088909853102761390579342692322723641755667989414758825919111747319417082430","1","0"],"c":["2463183151432828250104418104303566353346427879241396491902830060129937982711","8583608334138536004614694930271133127458004220774193962674173582521603759186","1"],"publicInputs":["35496476102218022411954850179653443322","266420555687711623212324141593370624656","20479760616052225895754597157548652202548706370970551586969474372834778795693","242108076058607163538102198631955675649","142667662805314151155817304537028292174","20864296715935232184768291025479986616839573165313814319339496966539463272408","14147941894629208776737080333130737791861963635182680712839892976578320559194","5"]}}},"votePackage":"eyJ2b3RlcyI6WzBdfQ=="}}} type=vote
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.375Z DBG vochain/app.go:355 > deliver tx hash=0eb46113d6cad43991c5afd7f9991f2dd0a8b5252ea15709cbc2aec908868aef height=12 tx={"Payload":{"NewProcess":{"process":{"blockCount":209,"censusOrigin":2,"censusRoot":"TYxJSF1JZsBrL0BGHJtkaakWrvwBx+QC7SekqpG8XFY=","censusURI":"ipfs://bafybeidsurfab4udztfik2kcdhbz6fu6phqsnhma4elzakkhxpihpjauiy","entityId":"VIvg5ZDss9ZWOteZrOwJZLtYOh8=","envelopeType":{},"maxCensusSize":10,"metadata":"ipfs://bafybeifp7s7waep53ey2cgkyc3fiqdm4oirnbps4c3krb2vtfvoizn4gbi","mode":{"autoStart":true,"dynamicCensus":true,"interruptible":true},"status":1,"tempSIKs":false,"voteOptions":{"costExponent":1,"maxCount":1,"maxTotalCost":2,"maxValue":2}},"txtype":1}}} type=newProcess
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.375Z INF state/process.go:39 > new election censusOrigin=OFF_CHAIN_TREE_WEIGHTED censusRoot=4d8c49485d4966c06b2f40461c9b6469a916aefc01c7e402ed27a4aa91bc5c56 censusURI=ipfs://bafybeidsurfab4udztfik2kcdhbz6fu6phqsnhma4elzakkhxpihpjauiy endBlock=222 entityId=548be0e590ecb3d6563ad799acec0964bb583a1f envelopeType={} height=12 maxCensusSize=10 mode={"autoStart":true,"dynamicCensus":true,"interruptible":true} processId=c5d2460186f7548be0e590ecb3d6563ad799acec0964bb583a1f020000000000 startBlock=13 status=1 voteOptions={"costExponent":1,"maxCount":1,"maxTotalCost":2,"maxValue":2}
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG state/account.go:173 > setting account 0x548be0e590ECB3d6563aD799ACeC0964bb583a1f process index to 1
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG state/account.go:202 > setAccount: address 0x548be0e590ECB3d6563aD799ACeC0964bb583a1f, nonce 0, infoURI ipfs://bafybeic7gfflbtphnnjppvvolslk6a3w4xfqfnfo7drsakaaom4asstluq, balance: 100000, delegates: [], processIndex: 1
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG ist/ist.go:124 > schedule IST action action=end-process height=222 id=c5d2460186f7548be0e590ecb3d6563ad799acec0964bb583a1f020000000000
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG state/account.go:258 > burning fee for tx NEW_PROCESS with cost 10 from account 0x548be0e590ECB3d6563aD799ACeC0964bb583a1f
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG state/account.go:202 > setAccount: address 0xFFfFfFffFFfffFFfFFfFFFFFffFFFffffFfFFFfF, nonce 0, infoURI , balance: 166, delegates: [], processIndex: 0
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG state/account.go:202 > setAccount: address 0x548be0e590ECB3d6563aD799ACeC0964bb583a1f, nonce 1, infoURI ipfs://bafybeic7gfflbtphnnjppvvolslk6a3w4xfqfnfo7drsakaaom4asstluq, balance: 99990, delegates: [], processIndex: 1
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z DBG ist/ist.go:207 > commit results action=commit-results height=12 id=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z INF results/compute.go:78 > computed results elapsed="188.312µs" process=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000 results=[90,0,0]
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.376Z INF ist/results.go:20 > committing results electionID=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000
testsuite_6144507814-miner1-1      | 2023-09-11T09:26:59.395Z INF vochain/app.go:340 > commit block height=12 txs=7

testsuite_6144507814-miner3-1      | 2023-09-11T09:26:59.369Z INF results/compute.go:78 > computed results elapsed="193.751µs" process=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000 results=[90,0,0]
testsuite_6144507814-miner3-1      | 2023-09-11T09:26:59.369Z INF ist/results.go:20 > committing results electionID=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000
testsuite_6144507814-miner3-1      | 2023-09-11T09:26:59.385Z INF vochain/app.go:340 > commit block height=12 txs=7

testsuite_6144507814-miner2-1      | 2023-09-11T09:26:59.39Z INF vochain/app.go:340 > commit block height=12 txs=7

testsuite_6144507814-miner0-1      | 2023-09-11T09:26:59.371Z INF results/compute.go:78 > computed results elapsed="95.76µs" process=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000 results=[90,0,0]
testsuite_6144507814-miner0-1      | 2023-09-11T09:26:59.371Z INF ist/results.go:20 > committing results electionID=c5d2460186f7adf0ecd3735744bb8f0e87833d5001337cb97fcc020000000000
testsuite_6144507814-miner0-1      | 2023-09-11T09:26:59.39Z INF vochain/app.go:340 > commit block height=12 txs=7
```

**Comment by altergui** [comment]
the second occurrence looks more weird at first sight, since it's failing on the pretty trivial (?) endpoint `/v2/chain/info` at 16:04:32.252

yet, some 20 ms before that i see a block start being commited, some process results being calculated... so it points in the same direction

```
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.203Z INF comet: finalizing commit of block hash={} num_txs=8 root=D6EC64EC3921545F19A0F7C5577CFB9B314549A39A960969FF32455FECD43065
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.224Z INF state/process.go:39 > new election censusOrigin=OFF_CHAIN_TREE_WEIGHTED censusRoot=ad67e08d8807bc569776818cff1d57c364d89c7f1a57caf4c7e682520bbdf5ab censusURI=ipfs://bafybeig4npx2km2xdh77zxmxunfbdwqgyueojztebcgucookd7s3bjorbm endBlock=139 entityId=4baf660645a9e27d1b617d58649a740366bd751b envelopeType={} height=10 maxCensusSize=10 mode={"autoStart":true} processId=c5d2460186f74baf660645a9e27d1b617d58649a740366bd751b020000000000 startBlock=11 status=1 voteOptions={"costExponent":1,"maxCount":1,"maxTotalCost":2,"maxValue":2}
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.231Z INF results/compute.go:78 > computed results elapsed=6.299343ms process=c5d2460186f70391dfb1048dd76cbd6a9141f7d6d6fd0f5e1b1a020400000000 results=[50,50,0]
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.231Z INF ist/results.go:20 > committing results electionID=c5d2460186f70391dfb1048dd76cbd6a9141f7d6d6fd0f5e1b1a020400000000
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.231Z INF comet: finalized block block_app_hash=1C6FD6193C90EFFF9322B0ACB5821D9BA3007DBA29221316B331DCB2CC5D2C51 height=10 num_txs_res=8 num_val_updates=0
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.231Z INF comet: executed block app_hash="\x1co�\x19<����\"����\x1d��\x00}�)\"\x13\x16�1ܲ�],Q" height=10
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.246Z INF vochain/app.go:339 > commit block height=10 txs=8
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.246Z INF comet: committed state block_app_hash=D6EC64EC3921545F19A0F7C5577CFB9B314549A39A960969FF32455FECD43065 height=10
testsuite_6148876892-seed-1        | 2023-09-11T16:04:32.257Z INF comet: indexed block events height=10

testsuite_6148876892-miner3-1      | 2023-09-11T16:04:32.231Z INF state/process.go:39 > new election censusOrigin=OFF_CHAIN_TREE_WEIGHTED censusRoot=ad67e08d8807bc569776818cff1d57c364d89c7f1a57caf4c7e682520bbdf5ab censusURI=ipfs://bafybeig4npx2km2xdh77zxmxunfbdwqgyueojztebcgucookd7s3bjorbm endBlock=139 entityId=4baf660645a9e27d1b617d58649a740366bd751b envelopeType={} height=10 maxCensusSize=10 mode={"autoStart":true} processId=c5d2460186f74baf660645a9e27d1b617d58649a740366bd751b020000000000 startBlock=11 status=1 voteOptions={"costExponent":1,"maxCount":1,"maxTotalCost":2,"maxValue":2}
testsuite_6148876892-miner3-1      | 2023-09-11T16:04:32.236Z INF results/compute.go:78 > computed results elapsed=4.35701ms process=c5d2460186f70391dfb1048dd76cbd6a9141f7d6d6fd0f5e1b1a020400000000 results=[50,50,0]
testsuite_6148876892-miner3-1      | 2023-09-11T16:04:32.236Z INF ist/results.go:20 > committing results electionID=c5d2460186f70391dfb1048dd76cbd6a9141f7d6d6fd0f5e1b1a020400000000
testsuite_6148876892-miner3-1      | 2023-09-11T16:04:32.257Z INF vochain/app.go:339 > commit block height=10 txs=8
```

which highlights the importance of fixing this, since it's likely affecting all endpoints :see_no_evil:

**Comment by altergui** [comment]
how on earth did this happen again?

[logs_21484518928.zip](https://github.com/vocdoni/vocdoni-node/files/14524708/logs_21484518928.zip)


https://github.com/vocdoni/vocdoni-node/actions/runs/8188910350/job/22392442949
```
2024-03-07T13:31:02.948Z FTL end2endtest/main.go:183 > found an unexpected error API error: 500 ({"error":"cannot fetch election: (02dadbeb747736e4a4b153685b96ec2fe78739fa6cc094f49021020000000000): while down, could not get value for key ee4cb3c0c18d3db97bf20f1db6fdb8b39e47d95fec77cc84aae9fd0d151d6822: key not found","code":5008}
)
goroutine 13 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x67
go.vocdoni.io/dvote/log.Fatal({0xc000577df8, 0x1, 0x1})
	go.vocdoni.io/dvote/log/log.go:209 +0xbc
main.setupAndRun({0x4edc2d0, {0x4d9e2f2, 0x88}, {0xc0006576e0, 0x2a}}, 0xc000796d40, 0xc0004e3d90)
	go.vocdoni.io/dvote/cmd/end2endtest/main.go:183 +0x55d
main.main.func2({0x4edc2d0, {0x4d9e2f2, 0x88}, {0xc0006576e0, 0x2a}}, 0xc0004e3d90, 0xc0001678f0)
	go.vocdoni.io/dvote/cmd/end2endtest/main.go:245 +0x226
created by main.main in goroutine 1
	go.vocdoni.io/dvote/cmd/end2endtest/main.go:267 +0x7fa
```
