### ISSUE TITLE
slice bounds out of range in pebble?

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#1130]
```
panic: runtime error: slice bounds out of range [:8882342] with capacity 0

goroutine 2878 [running]:
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).findSpliceForLevel(0xc000804178, {0xc00ba058d0, 0x6, 0x6}, 0x742f726f6f740000, 0x0?, 0x0?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/internal/batchskl/skl.go:399 +0x175
github.com/cockroachdb/pebble/internal/batchskl.(*Iterator).seekForBaseSplice(0xc0199d42e0, {0xc00ba058d0, 0x6, 0x6}, 0xc01237b950?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/internal/batchskl/iterator.go:216 +0x6b
github.com/cockroachdb/pebble/internal/batchskl.(*Iterator).SeekGE(0xc0199d42e0, {0xc00ba058d0, 0x6, 0x6}, 0x28?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/internal/batchskl/iterator.go:75 +0xb3
github.com/cockroachdb/pebble.(*batchIter).SeekGE(0xc0199d42d0, {0xc00ba058d0?, 0xc01237b950?, 0x0?}, 0x0?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/batch.go:1530 +0x66
github.com/cockroachdb/pebble.(*getIter).Next(0xc01af52e80)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/get_iter.go:135 +0xe85
github.com/cockroachdb/pebble.(*getIter).First(0x0?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/get_iter.go:66 +0x13
github.com/cockroachdb/pebble.(*Iterator).iterFirstWithinBounds(0xc01af52900)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/iterator.go:1960 +0xe2
github.com/cockroachdb/pebble.(*Iterator).First(0xc01af52900)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/iterator.go:1559 +0xe9
github.com/cockroachdb/pebble.(*DB).getInternal(0xc00335c000, {0xc00ba058d0, 0x6, 0x6}, 0xc000804000, 0x0)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/db.go:607 +0x3d1
github.com/cockroachdb/pebble.(*Batch).Get(0xc01d3624e0?, {0xc00ba058d0?, 0xc0163aa1c0?, 0x0?})
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20230620232302-06034ff014e0/batch.go:533 +0x2f
go.vocdoni.io/dvote/db/pebbledb.get({0x41aa6c0?, 0xc000804000?}, {0xc00ba058d0?, 0x33b24c0?, 0x1?})
	/home/p4u/repos/vocdoni/vocdoni-node/db/pebbledb/pebledb.go:20 +0x33
go.vocdoni.io/dvote/db/pebbledb.WriteTx.Get({0x7f4636da71e8?}, {0xc00ba058d0?, 0x100?, 0xc000268c00?})
	/home/p4u/repos/vocdoni/vocdoni-node/db/pebbledb/pebledb.go:65 +0x2b
go.vocdoni.io/dvote/db/prefixeddb.(*PrefixedWriteTx).Get(0xc017e811a0, {0x5a5499c, 0x4, 0x0?})
	/home/p4u/repos/vocdoni/vocdoni-node/db/prefixeddb/prefixeddb.go:117 +0x10c
go.vocdoni.io/dvote/tree/arbo.(*Tree).RootWithTx(...)
	/home/p4u/repos/vocdoni/vocdoni-node/tree/arbo/tree.go:181
go.vocdoni.io/dvote/tree/arbo.(*Tree).GetWithTx(0xc0189d8510, {0x7f466426b458, 0xc017e811a0}, {0xc00023ce88, 0x3, 0x8})
	/home/p4u/repos/vocdoni/vocdoni-node/tree/arbo/tree.go:530 +0x29c
go.vocdoni.io/dvote/tree.(*Tree).Get(0xc0189d86f8?, {0x7f466426b458?, 0xc017e811a0?}, {0xc00023ce88?, 0x0?, 0x0?})
	/home/p4u/repos/vocdoni/vocdoni-node/tree/tree.go:70 +0x77
go.vocdoni.io/dvote/statedb.(*TreeUpdate).SubTree(0xc0189d86c8, {{0xc00023ce88, 0x3, 0x8}, {0x3959421, 0x3}, 0xc0005d93c0})
	/home/p4u/repos/vocdoni/vocdoni-node/statedb/treeupdate.go:153 +0x10e
go.vocdoni.io/dvote/statedb.(*TreeUpdate).DeepSubTree(0x3989e29?, {0xc01d362af0?, 0x1, 0x7f4636e73940?})
	/home/p4u/repos/vocdoni/vocdoni-node/statedb/treeupdate.go:198 +0x8f
go.vocdoni.io/dvote/vochain/state.(*State).UpdateSIKRoots(0xc00332c3c0)
	/home/p4u/repos/vocdoni/vocdoni-node/vochain/state/sik.go:190 +0x1d7
go.vocdoni.io/dvote/vochain/state.(*State).Save(0xc00332c3c0)
	/home/p4u/repos/vocdoni/vocdoni-node/vochain/state/state.go:426 +0x234
go.vocdoni.io/dvote/vochain.(*BaseApplication).Commit(0xc003aea000, {0x5b35080?, 0x7f4636edd3e0?}, 0x7f46af0f3688?)
	/home/p4u/repos/vocdoni/vocdoni-node/vochain/app.go:352 +0x2d
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x0?, {0x41b4420?, 0x5b6abe0?}, 0x0?)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/abci/client/local_client.go:113 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc002ec9800, {0x41b4420, 0x5b6abe0})
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/proxy/app_conn.go:109 +0x168
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc000c96600, 0x6}}, {0xc000c96630, 0xd}, 0x1, 0x32, {{0xc0189fe660, ...}, ...}, ...}, ...)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/state/execution.go:394 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000c96600, 0x6}}, {0xc000c96630, 0xd}, 0x1, 0x32, {{0xc0189fe660, ...}, ...}, ...}, ...)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/state/execution.go:281 +0x1030
github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc0099181e0, 0x0)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/blocksync/reactor.go:508 +0x1457
created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 1
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/blocksync/reactor.go:124 +0x6e
exit status 2
```

**Comment by p4u** [comment]
ping @mvdan

**Comment by p4u** [comment]
The issue seems to happen when there are several calls to rTx.Get

I have fixed the previous error by caching the RootWithTx() value. But it crashed, with the same error, somewhere else:

```
panic: runtime error: slice bounds out of range [:8882123] with capacity 0

goroutine 3527 [running]:
github.com/cockroachdb/pebble/internal/batchskl.(*Skiplist).findSpliceForLevel(0xc000aaa538, {0xc010d60f90, 0x22, 0x22}, 0x742fc3a858f4005a, 0x3731560?, 0x0?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/internal/batchskl/skl.go:400 +0x175
github.com/cockroachdb/pebble/internal/batchskl.(*Iterator).seekForBaseSplice(0xc0171797b0, {0xc010d60f90, 0x22, 0x22}, 0xc017d534d0?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/internal/batchskl/iterator.go:216 +0x6b
github.com/cockroachdb/pebble/internal/batchskl.(*Iterator).SeekGE(0xc0171797b0, {0xc010d60f90, 0x22, 0x22}, 0x28?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/internal/batchskl/iterator.go:75 +0xb3
github.com/cockroachdb/pebble.(*batchIter).SeekGE(0xc0171797a0, {0xc010d60f90?, 0xc017d534d0?, 0x0?}, 0x0?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/batch.go:1554 +0x66
github.com/cockroachdb/pebble.(*getIter).Next(0xc00040fa90)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/get_iter.go:134 +0x10c5
github.com/cockroachdb/pebble.(*getIter).First(0x131023e?)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/get_iter.go:65 +0x13
github.com/cockroachdb/pebble.(*Iterator).iterFirstWithinBounds(0xc00040f500)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/iterator.go:2007 +0xe2
github.com/cockroachdb/pebble.(*Iterator).First(0xc00040f500)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/iterator.go:1605 +0xea
github.com/cockroachdb/pebble.(*DB).getInternal(0xc000b28900, {0xc010d60f90, 0x22, 0x22}, 0xc000aaa3c0, 0x0)
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/db.go:595 +0x3d1
github.com/cockroachdb/pebble.(*Batch).Get(0xc017c262c0?, {0xc010d60f90?, 0x0?, 0x0?})
	/home/p4u/go/pkg/mod/github.com/cockroachdb/pebble@v0.0.0-20231002124432-0f80e1841fc8/batch.go:553 +0x2f
go.vocdoni.io/dvote/db/pebbledb.get({0x422c820?, 0xc000aaa3c0?}, {0xc010d60f90?, 0x340abc0?, 0x1?})
	/home/p4u/repos/vocdoni/vocdoni-node/db/pebbledb/pebledb.go:21 +0x33
go.vocdoni.io/dvote/db/pebbledb.WriteTx.Get({0x0?}, {0xc010d60f90?, 0x0?, 0x0?})
	/home/p4u/repos/vocdoni/vocdoni-node/db/pebbledb/pebledb.go:69 +0x2b
go.vocdoni.io/dvote/db/prefixeddb.(*PrefixedWriteTx).Get(0xc017ef7950, {0xc020b755e0, 0x20, 0x3e9d5f0?})
	/home/p4u/repos/vocdoni/vocdoni-node/db/prefixeddb/prefixeddb.go:117 +0x10c
go.vocdoni.io/dvote/tree/arbo.(*Tree).down(0xc017efa9c0, {0x7f9c2021d748, 0xc017ef7950}, {0xc000799ce8, 0x3, 0x8}, {0xc020b755e0, 0x20, 0x20}, {0x0, ...}, ...)
	/home/p4u/repos/vocdoni/vocdoni-node/tree/arbo/navigate.go:24 +0xee
go.vocdoni.io/dvote/tree/arbo.(*Tree).GetWithTx(0xc017efa9c0, {0x7f9c2021d748, 0xc017ef7950}, {0xc000799ce8, 0x3, 0x8})
	/home/p4u/repos/vocdoni/vocdoni-node/tree/arbo/tree.go:549 +0x2e9
go.vocdoni.io/dvote/tree.(*Tree).Get(0xc016f9a8a8?, {0x7f9c2021d748?, 0xc017ef7950?}, {0xc000799ce8?, 0x0?, 0x0?})
	/home/p4u/repos/vocdoni/vocdoni-node/tree/tree.go:70 +0x77
go.vocdoni.io/dvote/statedb.(*TreeUpdate).SubTree(0xc016f9a878, {{0xc000799ce8, 0x3, 0x8}, {0x39b9d1b, 0x3}, 0xc0004e1280})
	/home/p4u/repos/vocdoni/vocdoni-node/statedb/treeupdate.go:153 +0x10e
go.vocdoni.io/dvote/statedb.(*TreeUpdate).DeepSubTree(0x39ea7db?, {0xc017c26af0?, 0x1, 0x50?})
	/home/p4u/repos/vocdoni/vocdoni-node/statedb/treeupdate.go:198 +0x8f
go.vocdoni.io/dvote/vochain/state.(*State).UpdateSIKRoots(0xc002c90900)
	/home/p4u/repos/vocdoni/vocdoni-node/vochain/state/sik.go:190 +0x1d7
go.vocdoni.io/dvote/vochain/state.(*State).Save(0xc002c90900)
	/home/p4u/repos/vocdoni/vocdoni-node/vochain/state/state.go:426 +0x234
go.vocdoni.io/dvote/vochain.(*BaseApplication).Commit(0xc0004a45a0, {0x5bddae0?, 0x7f9be12ecd10?}, 0x7f9c6b770878?)
	/home/p4u/repos/vocdoni/vocdoni-node/vochain/app.go:352 +0x2d
github.com/cometbft/cometbft/abci/client.(*localClient).Commit(0x0?, {0x4236640?, 0x5c13780?}, 0x0?)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/abci/client/local_client.go:113 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).Commit(0xc000b0fc50, {0x4236640, 0x5c13780})
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/proxy/app_conn.go:109 +0x168
github.com/cometbft/cometbft/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc000869aa0, 0x6}}, {0xc000869af0, 0xd}, 0x1, 0x32, {{0xc017efc120, ...}, ...}, ...}, ...)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/state/execution.go:394 +0x213
github.com/cometbft/cometbft/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc000869aa0, 0x6}}, {0xc000869af0, 0xd}, 0x1, 0x32, {{0xc017efc120, ...}, ...}, ...}, ...)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/state/execution.go:281 +0x1030
github.com/cometbft/cometbft/blocksync.(*Reactor).poolRoutine(0xc000aaa780, 0x0)
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/blocksync/reactor.go:508 +0x1457
created by github.com/cometbft/cometbft/blocksync.(*Reactor).OnStart in goroutine 1
	/home/p4u/go/pkg/mod/github.com/cometbft/cometbft@v0.38.0/blocksync/reactor.go:124 +0x6e
exit status 2
```

**Comment by p4u** [comment]
I can confirm the issue remains on the last pebble release.

**Comment by p4u** [comment]
I have detected the issue using the commit https://github.com/vocdoni/vocdoni-node/commit/533030d5e306d673ffdb3a901ccc40ecd09c3e8d

I'm not certain how to reproduce it yet, it happened in my local docker compose deployment after filling the chain with several transactions for some hours.

Switching to goleveldb db-backend, the issue disappears.

**Comment by p4u** [comment]
Wow... it just happened on the CI (or very similar): https://github.com/vocdoni/vocdoni-node/actions/runs/6386257150/job/17332589319

I really don't understand why it is this happening now...

**Comment by altergui** [comment]
perfect, so i could reproduce it reliably on 9a024fc3 with 

```sh
git checkout 9a024fc3
go1.21.1 test ./vochain/state/ -run TestStateBasic -count=50
```

but the panic doesn't happen in current main (e48b7068895c526722b5edcbad3ae836e6d3c4ec)
so git bisect FTW

```sh
git bisect start 9a024fc3 main
git bisect run go1.21.1 test ./vochain/state/ -run TestStateBasic -count=50
```

says 

> 533030d5e306d673ffdb3a901ccc40ecd09c3e8d is the first bad commit

```diff
commit 533030d5e306d673ffdb3a901ccc40ecd09c3e8d
Author: p4u <pau@dabax.net>
Date:   Tue Oct 3 00:28:09 2023 +0200

    pebble: crazy lock all operations and update to last pebble version

 db/pebbledb/pebledb.go | 50 ++++++++++++++++++++++++++++++++++++++++++++------
 go.mod                 | 22 +++++++++++++++-------
 go.sum                 | 38 ++++++++++++++++++++++++++++++++++++++
 vochain/state/state.go |  4 ----
 4 files changed, 97 insertions(+), 17 deletions(-)
```

**Comment by altergui** [comment]
manually bisected 533030d and the problematic change is 

```diff
diff --git a/vochain/state/state.go b/vochain/state/state.go
index f24b00d7..1ab58121 100644
--- a/vochain/state/state.go
+++ b/vochain/state/state.go
@@ -408,13 +408,9 @@ func (v *State) Save() ([]byte, error) {
        v.tx.Lock()
        defer v.tx.Unlock()
        err := func() error {
-               var err error
                if err := v.tx.Commit(height); err != nil {
                        return fmt.Errorf("cannot commit statedb tx: %w", err)
                }
-               if v.tx.TreeTx, err = v.store.BeginTx(); err != nil {
-                       return fmt.Errorf("cannot begin statedb tx: %w", err)
-               }
                return nil
        }()
        if err != nil {
```

**Comment by altergui** [comment]
applying that, (without upgrading pebbledb or anything) makes TestStateBasic panic

**Comment by p4u** [comment]
Amazing finding!
So, I removed this because beginBlock() already resets the transaction, so I see no need to do it here. But probably there is some kind of Race I'm not able to understand here.

**Comment by mvdan** [comment]
I think the fix here was figured out?

**Comment by altergui** [comment]
AFAIU yes, this never hit main
