### ISSUE TITLE
ci: failed with "proof not valid: process id mismatch"

### ISSUE THREAD

**Issue by altergui** [vocdoni/vocdoni-node#1262]
strangest failure ever:
https://github.com/vocdoni/vocdoni-node/actions/runs/8140281454/job/22245172838?pr=1261
[logs_21354759791.zip](https://github.com/vocdoni/vocdoni-node/files/14482654/logs_21354759791.zip)

```
2024-03-04T12:42:20.161Z INF end2endtest/helpers.go:615 > sent votes errors=6 timeouts=0 total=10
2024-03-04T12:42:20.162Z FTL end2endtest/main.go:183 > error in sendVotes map[0:API error: 500 ({"error":"vochain SendTx failed: voteTx: proof not valid: proof not valid: process id mismatch 02dadbeb7477372105ed2b35acd347b145d4ce3d38ccc9616be3020200000000 != 4e40922dceb440298317110edaca94bd580661a4431950379650a26e10e9","code":5001}
) 1:API error: 500 ({"error":"vochain SendTx failed: voteTx: proof not valid: proof not valid: process id mismatch 02dadbeb7477372105ed2b35acd347b145d4ce3d38ccc9616be3020200000000 != 4e40922dceb440298317110edaca94bd580661a4431950379650a26e10e9","code":5001}
) 2:API error: 500 ({"error":"vochain SendTx failed: voteTx: proof not valid: proof not valid: process id mismatch 02dadbeb7477372105ed2b35acd347b145d4ce3d38ccc9616be3020200000000 != 4e40922dceb440298317110edaca94bd580661a4431950379650a26e10e9","code":5001}
) 6:API error: 500 ({"error":"vochain SendTx failed: voteTx: proof not valid: proof not valid: process id mismatch 02dadbeb7477372105ed2b35acd347b145d4ce3d38ccc9616be3020200000000 != 4e40922dceb440298317110edaca94bd580661a4431950379650a26e10e9","code":5001}
) 7:API error: 500 ({"error":"vochain SendTx failed: voteTx: proof not valid: proof not valid: process id mismatch 02dadbeb7477372105ed2b35acd347b145d4ce3d38ccc9616be3020200000000 != 4e40922dceb440298317110edaca94bd580661a4431950379650a26e10e9","code":5001}
) 8:API error: 500 ({"error":"vochain SendTx failed: voteTx: proof not valid: proof not valid: process id mismatch 02dadbeb7477372105ed2b35acd347b145d4ce3d38ccc9616be3020200000000 != 4e40922dceb440298317110edaca94bd580661a4431950379650a26e10e9","code":5001}
)]
goroutine 39 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x67
go.vocdoni.io/dvote/log.Fatal({0xc000061df8, 0x1, 0x1})
	go.vocdoni.io/dvote/log/log.go:209 +0xbc
main.setupAndRun({0x4ed9f80, {0x4da04de, 0xac}, {0xc00099c180, 0x3b}}, 0xc0003fa680, 0xc0003bc0b0)
	go.vocdoni.io/dvote/cmd/end2endtest/main.go:183 +0x55d
main.main.func2({0x4ed9f80, {0x4da04de, 0xac}, {0xc00099c180, 0x3b}}, 0xc0003bc0b0, 0xc00015e970)
	go.vocdoni.io/dvote/cmd/end2endtest/main.go:245 +0x226
created by main.main in goroutine 1
	go.vocdoni.io/dvote/cmd/end2endtest/main.go:267 +0x7fa
```

**Comment by altergui** [comment]
haven't seen this again, closing
