### ISSUE TITLE
bug: gateway crash

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#176]
Under high load
```
panic: Remove(e) with false head

goroutine 6637427 [running]:
github.com/tendermint/tendermint/libs/clist.(*CList).Remove(0xc003e35f90, 0xc04be58900, 0xc04d288e50, 0xc0361ecdf8)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/libs/clist/clist.go:370 +0x285
github.com/tendermint/tendermint/mempool.(*CListMempool).removeTx(0xc01154b1e0, 0xc029fd4000, 0x35b, 0x35b, 0xc04be58900, 0xc0361ece01)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/mempool/clist_mempool.go:361 +0x51
github.com/tendermint/tendermint/mempool.(*CListMempool).RemoveTxByKey(0xc01154b1e0, 0x3973d4d8b6cd19cd, 0xaa4167b1a56dc290, 0x73d528148251d68, 0x3173de66cd9a3851, 0xc003bcdd01)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/mempool/clist_mempool.go:376 +0xe9
go.vocdoni.io/dvote/vochain.(*State).CachePurge(0xc0032391a0, 0x21d2)
        /src/vochain/cache.go:80 +0x402
created by go.vocdoni.io/dvote/vochain.(*BaseApplication).BeginBlock
        /src/vochain/app.go:315 +0x40c
```

**Comment by p4u** [comment]
I'm not sure how to reproduce it and the last changes on the code could have fixed it. However @mvdan if you could take a look on the reason of this Panic maybe we can find what was the originator (if tendermint or vocdoni)

**Comment by mvdan** [comment]
@p4u I looked a bit into this. It would be helpful if we can go over the code together tomorrow for 20m, because I want to understand what the code is trying to do better. It will help me with replacing the LRU cache, too.
