### ISSUE TITLE
vochain sigsev on Rollback

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#178]
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x29753a2]

goroutine 1 [running]:
go.vocdoni.io/dvote/vochain.(*State).Rollback(0xc001ed4660)
        /src/vochain/state.go:576 +0x102
go.vocdoni.io/dvote/vochain.(*BaseApplication).Info(0xc002d65c80, 0x0, 0x0, 0xb, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /src/vochain/app.go:225 +0x253
github.com/tendermint/tendermint/abci/client.(*localClient).InfoSync(0xc002b4cc00, 0x0, 0x0, 0xb, 0x8, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/abci/client/local_client.go:218 +0x102
github.com/tendermint/tendermint/proxy.(*appConnQuery).InfoSync(0xc004c0d810, 0x0, 0x0, 0xb, 0x8, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/proxy/app_conn.go:155 +0x5e
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0056e67b0, 0x37c5138, 0xc0018f36c0, 0xc0079ee4b0, 0xc00a037650)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:244 +0x90
github.com/tendermint/tendermint/node.doHandshake(0x37bc030, 0xc004c0ccd0, 0xb, 0x0, 0x0, 0x0, 0xc0049ba180, 0x16, 0x1, 0x0, ...)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc004be7cc0, 0x378bca0, 0xc004e50d20, 0xc004a3f310, 0x374fa20, 0xc0035ab0f8, 0xc004a3f3d0, 0x34cbef0, 0xc004a3f3e0, 0x379b750, ...)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.10/node/node.go:715 +0x2025
go.vocdoni.io/dvote/vochain.newTendermint(0xc002d65c80, 0xc0001594a0, 0xc00078d800, 0xb99, 0xb9a, 0x0, 0x0, 0x0)
        /src/vochain/start.go:274 +0x1336
go.vocdoni.io/dvote/vochain.(*BaseApplication).SetNode(0xc002d65c80, 0xc0001594a0, 0xc00078d800, 0xb99, 0xb9a, 0x1, 0x1)
        /src/vochain/app.go:73 +0x5a
go.vocdoni.io/dvote/vochain.NewVochain(0xc0001594a0, 0xc00078d800, 0xb99, 0xb9a, 0xc0002319d0)
        /src/vochain/start.go:34 +0x1cf
go.vocdoni.io/dvote/service.Vochain(0xc0001594a0, 0x1, 0xc00084f578, 0xc002520fc0, 0x37bbbb8, 0xc0019e4870, 0x0, 0xc0019b2690, 0x0, 0x0, ...)
        /src/service/vochain.go:110 +0x4fa
main.main()
        /src/cmd/dvotenode/dvotenode.go:481 +0x1b88
2021/05/13 16:18:28 WARNING: proto: file "vochain/vochain.proto" has a name conflict over dvote.types.v1.UNKNOWN
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2021/05/13 16:18:28 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

vocdoni dvote version "7471b01-dirty"
2021/05/13 16:18:28 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
badger 2021/05/13 16:18:32 INFO: All 3 tables opened in 1ms
badger 2021/05/13 16:18:32 INFO: Discard stats nextEmptySlot: 3
badger 2021/05/13 16:18:32 INFO: Set nextTxnTs to 390
```

**Comment by mvdan** [comment]
I'm not sure how we got to a nil pointer there, but the good news is that there's an easy way to avoid that entirely - by not using a pointer in the field type. I'll send a PR shortly.
