### ISSUE TITLE
bug:  database entry point either missing or corrupted

### ISSUE THREAD

**Issue by vdo** [vocdoni/vocdoni-node#222]
**Describe the bug**
Error when restarting the node because of corrupted database.

**To Reproduce (please complete the following information)**
Unknown

**Current behavior**
```

2021-06-14T07:59:29Z	INFO	dvotenode/dvotenode.go:367	logger construction succeeded at level debug with output stdout
2021-06-14T07:59:29Z	DEBUG	dvotenode/dvotenode.go:373	initializing config {W3Config:0xc00005fb40 VochainConfig:0xc0000e9340 Ipfs:0xc000c38910 EthConfig:0xc0003c8250 EthEventConfig:0xc000bd3068 API:0xc00038eb00 Metrics:0xc000bd3090 LogLevel:debug LogOutput:stdout LogErrorFile: DataDir:/app/run SaveConfig:false Mode:oracle Dev:false}
2021-06-14T07:59:29Z	INFO	dvotenode/dvotenode.go:381	config file loaded successfully. Reminder: CLI flags have preference
2021-06-14T07:59:29Z	INFO	dvotenode/dvotenode.go:413	starting vocdoni node version "f3db6cb-dirty" in oracle mode
2021-06-14T07:59:29Z	INFO	dvotenode/dvotenode.go:446	adding custom signing key
2021-06-14T07:59:29Z	INFO	dvotenode/dvotenode.go:452	using custom pubKey 03464bf26fc19995624cb20c3e8701c3c67f6918a19acce2556fc29bdca87eba41
2021-06-14T07:59:29Z	INFO	service/proxy.go:16	creating proxy service, listening on 0.0.0.0:9090
2021-06-14T07:59:29Z	INFO	mhttp/proxy.go:133	starting go-chi http server
2021-06-14T07:59:29Z	INFO	mhttp/proxy.go:147	proxy ready at http://[::]:9090
2021-06-14T07:59:29Z	INFO	metrics/metrics.go:22	prometheus metrics ready at: /metrics
2021-06-14T07:59:29Z	INFO	service/vochain.go:28	creating vochain service for network main
2021-06-14T07:59:29Z	INFO	service/vochain.go:50	vochain listening on: 0.0.0.0:26656
2021-06-14T07:59:29Z	INFO	service/vochain.go:51	vochain exposed IP address: 95.217.219.72:26656
2021-06-14T07:59:29Z	INFO	service/vochain.go:52	vochain RPC listening on: 127.0.0.1:26657
2021-06-14T07:59:29Z	INFO	service/vochain.go:70	found genesis file
2021-06-14T07:59:29Z	INFO	service/vochain.go:88	local genesis matches with the hardcoded genesis
2021-06-14T07:59:29Z	INFO	vochain/state.go:117	initializing state db store
2021-06-14T07:59:29Z	FATAL	vochain/start.go:31	cannot initialize vochain application: cannot create vochain state: (cannot init state db: database entry point either missing or corrupted)
go.vocdoni.io/dvote/vochain.NewVochain
	go.vocdoni.io/dvote/vochain/start.go:31
go.vocdoni.io/dvote/service.Vochain
	go.vocdoni.io/dvote/service/vochain.go:110
main.main
	go.vocdoni.io/dvote/cmd/dvotenode/dvotenode.go:502
runtime.main
	runtime/proc.go:225
```

**Expected behavior**
The node starts from previous state with no errors

- Commit hash: release-1.1 "f3db6cb-dirty"

**Additional context**
This is an oracle in the production environment

**Comment by vdo** [comment]
Some errors before reaching the corrupted state:
```
2021-06-14T07:05:13Z    DEBUG    vochain/app.go:344      deliver tx: {"vote":{"nonce":"/8eh8IjIUOOmkQSd8K4Cl4+ZKu4A0mW6qAxgx3WZPN8=", "processId":"ukKGKjkKzCIVf0hjVOJQezaRYPnUxgBfGKO6ZN4xSSQ=", "proof":{"graviton":{"siblings":"AQER//+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABTJ2+nIlbsl+/q/Ug3M3MquFLD/8kFTculBLkQJrpm2mYbNQeCq3zTc6MO518xyTNALoogmQNXb0w5AbSiuFmZnUVWkLxI+hqstslcTqkpFljSFaTvWStnBmvACnbD5dhWXNnldOQylZch2ytIETHsZgkaflkuAYkGCZR1yqkbm0gUuRQzZJZh/My/Klev02QEdMDBr7h8rJyyeA4mzq39uRX0penB6dUUns9iwWiLIYFaH6HD5K+e7I1KgJw/R4Q1EgnfD1h95vVKsJnCq84/kGBSd4FBk3Yhp1GFXwucdjtoYH5mopMMExzzV35TOxeIBP/SzlmgtXC5+JFskZRgVuMjtVR4r06CGPdNOe9khY4bRVIQCmPBumpf2e07fR8OpLi6wI4hWKCLyutcpEf0gjNbW+nEgod/v/aG+7Nz3yhf9dKk/x6xRhkk1I2K4gA5n0pG88Qc48fO4i3UE0mkuTCXv2BSwc3l54VI+DqaVtF8sshTAflaHLpKO1AM3iSh59oUrVx5x2kAnnmLKUgPQChde5KUMOdtyknl2MwOhFONwsihn8Bogvq5kY1zSBLOjywh5Huv1lYvWrrAE218iej5VhIpFR3YUcYD/vQfDja2i948OfJzjqR8IhNJoUXD7kXcnRxa+pvdccnGTOotafnn80ezIg/FeV0TsoaT+f6ZodEjDK14g/mXZJ+tAVwvFjn3W2LAGeVi6Dxm+zb9AA=="}}, "votePackage":"qPSzCUxiYGd0ds/IGxg+yOr2Q+p2AgMphdBacyqmA1pNL/iAO9iCZ+h8sPo+Qt81pG6I8C2NunwAV/kas2j+ekhY2KRpBmQsA4+v8wzipPYnKhVGrTBR8KOvNpeN6VaHdEXMdr0H1CNlfi+PWieGxArWsPcTeK8AL6EzzdtlB41ZGv4zI6wfHtqU", "nullifier":"", "encryptionKeyIndexes":[1, 2]}}A7684210EB4A20F437E1AE99F3EDCDA697BF8CCC8A9C55586EC:1:58F144DBE266 2021-06-14 07:04:32.530580534 +0000 UTC ValidatorSet{
  Proposer: Validator{314D17BBE991FBD3D234E5C62CFD5D0717123C95 PubKeyEd25519{14B120FE981D178759D3AD26BDE77FCFDF69FC425E3EEF644ACC8B9EBB11342D} VP:10 A:-40}
  Validators:
    Validator{314D17BBE991FBD3D234E5C62CFD5D0717123C95 PubKeyEd25519{14B120FE981D178759D3AD26BDE77FCFDF69FC425E3EEF644ACC8B9EBB11342D} VP:10 A:-40}
    Validator{34B048A4A720E6B3918CF8B75CF12555080465E5 PubKeyEd25519{685FFE59A36CE6D92744C4694CF3B8F532592E60DCB4EF891FCB9C904E5F4CD5} VP:10 A:10}
    Validator{6DB4FEE1D370907B31196B493714FC0F45C62DED PubKeyEd25519{47B53E1F1C93AEF95771C126D6C73CD30C3CDC5A69E31836E3B9E6A639A46137} VP:10 A:10}
    Validator{71AA2FEFA96447BC5AEF9FD928F3F8ED57E695CF PubKeyEd25519{8B123DD4FF8C3F58E2548CB527042AC11759219C6C548D16AF2B40CE884C1829} VP:10 A:10}
    Validator{AA9CC01B46BDD1AC9E2197BB9B84993CCDF880B2 PubKeyEd25519{1FAA04305ACD15E41E9ABF4A8318EAFF0564D64650D5513F275C159D527E2BD2} VP:10 A:10}
} ValidatorSet{
  Proposer: Validator{AA9CC01B46BDD1AC9E2197BB9B84993CCDF880B2 PubKeyEd25519{1FAA04305ACD15E41E9ABF4A8318EAFF0564D64650D5513F275C159D527E2BD2} VP:10 A:0}
  Validators:
    Validator{34B048A4A720E6B3918CF8B75CF12555080465E5 PubKeyEd25519{685FFE59A36CE6D92744C4694CF3B8F532592E60DCB4EF891FCB9C904E5F4CD5} VP:10 A:0}
    Validator{6DB4FEE1D370907B31196B493714FC0F45C62DED PubKeyEd25519{47B53E1F1C93AEF95771C126D6C73CD30C3CDC5A69E31836E3B9E6A639A46137} VP:10 A:0}
    Validator{71AA2FEFA96447BC5AEF9FD928F3F8ED57E695CF PubKeyEd25519{8B123DD4FF8C3F58E2548CB527042AC11759219C6C548D16AF2B40CE884C1829} VP:10 A:0}
    Validator{AA9CC01B46BDD1AC9E2197BB9B84993CCDF880B2 PubKeyEd25519{1FAA04305ACD15E41E9ABF4A8318EAFF0564D64650D5513F275C159D527E2BD2} VP:10 A:0}
} ValidatorSet{
  Proposer: Validator{71AA2FEFA96447BC5AEF9FD928F3F8ED57E695CF PubKeyEd25519{8B123DD4FF8C3F58E2548CB527042AC11759219C6C548D16AF2B40CE884C1829} VP:10 A:-10}
  Validators:
    Validator{314D17BBE991FBD3D234E5C62CFD5D0717123C95 PubKeyEd25519{14B120FE981D178759D3AD26BDE77FCFDF69FC425E3EEF644ACC8B9EBB11342D} VP:10 A:-10}
    Validator{34B048A4A720E6B3918CF8B75CF12555080465E5 PubKeyEd25519{685FFE59A36CE6D92744C4694CF3B8F532592E60DCB4EF891FCB9C904E5F4CD5} VP:10 A:-10}
    Validator{6DB4FEE1D370907B31196B493714FC0F45C62DED PubKeyEd25519{47B53E1F1C93AEF95771C126D6C73CD30C3CDC5A69E31836E3B9E6A639A46137} VP:10 A:-10}
    Validator{71AA2FEFA96447BC5AEF9FD928F3F8ED57E695CF PubKeyEd25519{8B123DD4FF8C3F58E2548CB527042AC11759219C6C548D16AF2B40CE884C1829} VP:10 A:-10}
    Validator{AA9CC01B46BDD1AC9E2197BB9B84993CCDF880B2 PubKeyEd25519{1FAA04305ACD15E41E9ABF4A8318EAFF0564D64650D5513F275C159D527E2BD2} VP:10 A:40}
} 1 {{10485760 -1 10000} {100000 10µs 0} {[ed25519]} {0}} 1 [223 100 110 59 134 122 205 189 23 197 249 20 190 167 112 249 177 19 209 68 18 84 159 110 86 197 73 191 137 71 97 3] [101 238 208 105 233 152 112 218 188 67 226 203 137 33 226 183 38 196 253 80 64 99 47 126 52 134 71 3 135 66 108 213]}
Did you reset Tendermint without resetting your application's data?

goroutine 1 [running]:
github.com/tendermint/tendermint/consensus.assertAppHashEqualsOneFromState(0xc00eaa46c0, 0x20, 0x20, 0xb, 0x0, 0x0, 0x0, 0xc00ea25530, 0x15, 0x1, ...)
        github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:525 +0x1e5
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(0xc00ea92868, 0xb, 0x0, 0x0, 0x0, 0xc00ea25530, 0x15, 0x1, 0x39caf, 0xc00ea41700, ...)
        github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:488 +0x378
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(0xc009f86868, 0xb, 0x0, 0x0, 0x0, 0xc00ea25530, 0x15, 0x1, 0x39caf, 0xc00ea41700, ...)
        github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:393 +0x8f0
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00ea92868, 0x334e158, 0xc000d9e1a0, 0xc00afe24b0, 0xc00ea51560)
        github.com/tendermint/tendermint@v0.34.10/consensus/replay.go:268 +0x458
github.com/tendermint/tendermint/node.doHandshake(0x3346350, 0xc00ea3ecd0, 0xb, 0x0, 0x0, 0x0, 0xc00ea25530, 0x15, 0x1, 0x39caf, ...)
        github.com/tendermint/tendermint@v0.34.10/node/node.go:308 +0x1d8
github.com/tendermint/tendermint/node.NewNode(0xc00233c280, 0x331b8d0, 0xc005548280, 0xc002114b10, 0x32e4600, 0xc003f5a978, 0xc002114bd0, 0x30a37d0, 0xc002114be0, 0x33290c8, ...)
        github.com/tendermint/tendermint@v0.34.10/node/node.go:715 +0x2025
go.vocdoni.io/dvote/vochain.newTendermint(0xc001f054a0, 0xc00033f760, 0xc002730000, 0xf45, 0xf46, 0x0, 0x0, 0x0)
        go.vocdoni.io/dvote/vochain/start.go:298 +0x1336
go.vocdoni.io/dvote/vochain.(*BaseApplication).SetNode(0xc001f054a0, 0xc00033f760, 0xc002730000, 0xf45, 0xf46, 0x1, 0x1)
        go.vocdoni.io/dvote/vochain/app.go:63 +0x5a
go.vocdoni.io/dvote/vochain.NewVochain(0xc00033f760, 0xc002730000, 0xf45, 0xf46, 0xc000f0da78)
        go.vocdoni.io/dvote/vochain/start.go:34 +0x1cf
go.vocdoni.io/dvote/service.Vochain(0xc00033f760, 0x101, 0xc000110450, 0x0, 0x0, 0x0, 0xc, 0xc00145fd70, 0x0, 0x0, ...)
        go.vocdoni.io/dvote/service/vochain.go:110 +0x4fa
main.main()
        go.vocdoni.io/dvote/cmd/dvotenode/dvotenode.go:502 +0x17e8
2021/06/14 07:05:32 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```
next restart...


```
2021-06-14T07:05:33Z    INFO     service/vochain.go:70   found genesis file
2021-06-14T07:05:33Z    INFO     service/vochain.go:88   local genesis matches with the hardcoded genesis
2021-06-14T07:05:33Z    INFO     vochain/state.go:117    initializing state db store
2021-06-14T07:05:33Z    INFO     vochain/state.go:133    state tree load took 40.881697ms
2021-06-14T07:05:33Z    INFO     vochain/state.go:85     loading last safe state db version, this could take a while...
2021-06-14T07:05:33Z    DEBUG    middleware/logger.go:150        "GET http://oracle.vocdoni.net:9090/metrics HTTP/1.1" from 95.217.216.185:33210 - 200 1543B in 1.994049ms
2021-06-14T07:05:51Z    WARN     vochain/state.go:89     no db version available: version does not exist, restarting vochain database
2021-06-14T07:05:51Z    FATAL    vochain/start.go:31     cannot initialize vochain application: cannot create vochain state: (cannot remove dataDir unlinkat /app/run/vochain/data/versions.db: directory not empty)
go.vocdoni.io/dvote/vochain.NewVochain
        go.vocdoni.io/dvote/vochain/start.go:31
go.vocdoni.io/dvote/service.Vochain
        go.vocdoni.io/dvote/service/vochain.go:110
main.main
        go.vocdoni.io/dvote/cmd/dvotenode/dvotenode.go:502
runtime.main
        runtime/proc.go:225
2021/06/14 07:06:11 WARNING: proto: file "pb.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

```
After this, the db is corrupted and you get the log described above

**Comment by p4u** [comment]
Looks like IAVL is getting corrupted for some reason... That's bad however we should get rid of IAVL pretty soon.
