### ISSUE TITLE
bug: Miner OOM crash with many goroutines from tendermint/p2p

### ISSUE THREAD

**Issue by ed255** [vocdoni/vocdoni-node#315]
The node crashed after a constant increase in memory consumption with `fatal error: out of memory allocating heap arena metadata` at 2021-10-09T21:11:37Z
Memory consumption graph (from Grafana):
![image](https://user-images.githubusercontent.com/24987329/136813424-9c6ee0e7-9f73-4a3d-ab9e-88d1c23d7b7c.png)

Sample goroutine stack trace:
```
goroutine 1643254 [chan send, 1324 minutes]:
github.com/tendermint/tendermint/consensus.(*Reactor).Receive(0xc001d28380, 0x22, {0x232be90, 0xc01e330540}, {0xc011f24000, 0x18, 0x7f3a6f0ed5b8})
        github.com/tendermint/tendermint@v0.34.13/consensus/reactor.go:337 +0x16d2
github.com/tendermint/tendermint/p2p.createMConnection.func1(0x22, {0xc011f24000, 0xbe, 0x2710})
        github.com/tendermint/tendermint@v0.34.13/p2p/peer.go:390 +0x20e
github.com/tendermint/tendermint/p2p/conn.(*MConnection).recvRoutine(0xc015691b80)
        github.com/tendermint/tendermint@v0.34.13/p2p/conn/connection.go:647 +0x3bd
created by github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStart
        github.com/tendermint/tendermint@v0.34.13/p2p/conn/connection.go:231 +0x231
```
At the crash there were 7766 goroutines like this one.  This is a count from the trace of goroutines creation points:
```
      1 created by github.com/cockroachdb/pebble/record.NewLogWriter
      1 created by github.com/golang/glog.init.0
      1 created by github.com/ipfs/go-log/writer.NewMirrorWriter
      1 created by github.com/libp2p/go-tcp-transport.(*aggregatingCollector).Collect.func1
      1 created by github.com/tendermint/tendermint/consensus.(*Reactor).OnStart
      1 created by github.com/tendermint/tendermint/consensus.(*timeoutTicker).OnStart
      1 created by github.com/tendermint/tendermint/libs/pubsub.(*Server).OnStart
      1 created by github.com/tendermint/tendermint/node.(*Node).startRPC
      1 created by github.com/tendermint/tendermint/p2p.(*MultiplexTransport).Listen
      1 created by github.com/tendermint/tendermint/p2p/pex.(*addrBook).OnStart
      1 created by github.com/tendermint/tendermint/p2p/pex.(*Reactor).OnStart
      1 created by github.com/tendermint/tendermint/p2p.(*Switch).OnStart
      1 created by github.com/tendermint/tendermint/proxy.(*multiAppConn).OnStart
      1 created by github.com/tendermint/tendermint/state/txindex.(*IndexerService).OnStart
      1 created by go.opencensus.io/stats/view.init.0
      1 created by go.vocdoni.io/dvote/db/pebbledb.New
      1 created by go.vocdoni.io/dvote/multirpc/transports/mhttp.(*Proxy).Init
      1 created by main.main
      1 created by os/signal.Notify.func1.1
      2 created by github.com/cockroachdb/pebble.(*tableCacheShard).init
      2 created by github.com/cockroachdb/pebble/vfs.(*diskHealthCheckingFile).startTicker
      2 created by github.com/rjeczalik/notify.newNonrecursiveTree
      2 created by github.com/tendermint/tendermint/libs/autofile.OpenAutoFile
      3 created by github.com/syndtr/goleveldb/leveldb.newSession
      3 created by github.com/syndtr/goleveldb/leveldb/util.NewBufferPool
      3 created by go.vocdoni.io/dvote/service.Vochain
      9 created by github.com/tendermint/tendermint/evidence.(*Reactor).AddPeer
      9 created by github.com/tendermint/tendermint/mempool.(*Reactor).AddPeer
      9 created by github.com/tendermint/tendermint/p2p.(*peer).OnStart
     12 created by github.com/syndtr/goleveldb/leveldb.openDB
     28 created by github.com/tendermint/tendermint/consensus.(*Reactor).AddPeer
   7777 created by github.com/tendermint/tendermint/p2p/conn.(*MConnection).OnStart
```
The last one is the point where the 7766 goroutines stuck at `github.com/tendermint/tendermint/consensus.(*Reactor).Receive` were created.

This only affected one miner, and not the rest, which is weird.

**Comment by altergui** [comment]
reading the code, i believe i understand what happened (i might be wrong, tho)

snippet at `github.com/tendermint/tendermint@v0.34.13/consensus/state.go:764`
```go
		case mi = <-cs.internalMsgQueue:
			err := cs.wal.WriteSync(mi) // NOTE: fsync
			if err != nil {
				panic(fmt.Sprintf(
					"failed to write %v msg to consensus WAL due to %v; check your file system and restart the node",
					mi, err,
				))
			}
```
that `WriteSync` failed for whatever reason, triggering panic()
...BUT, a bit earlier there's a recover()

`github.com/tendermint/tendermint@v0.34.13/consensus/state.go:724`
```go

	defer func() {
		if r := recover(); r != nil {
			cs.Logger.Error("CONSENSUS FAILURE!!!", "err", r, "stack", string(debug.Stack()))
			// stop gracefully
			//
			// NOTE: We most probably shouldn't be running any further when there is
			// some unexpected panic. Some unknown error happened, and so we don't
			// know if that will result in the validator signing an invalid thing. It
			// might be worthwhile to explore a mechanism for manual resuming via
			// some console or secure RPC system, but for now, halting the chain upon
			// unexpected consensus bugs sounds like the better option.
			onExit(cs)
		}
	}()
```

so instead of dying, the whole thing continued running, but without the (panic'ed) `receiveRoutine()` which normally reads the chan. So `consensus.(*Reactor).Receive()` goroutines (which try to send over that chan) started piling up until OOM.

**Comment by altergui** [comment]
tendermint master (and also v0.35.x branch) still have this code untouched 
recover: https://github.com/tendermint/tendermint/blob/master/internal/consensus/state.go#L851
panic: https://github.com/tendermint/tendermint/blob/master/internal/consensus/state.go#L893

**Comment by jordipainan** [comment]
@altergui can you update on this issue? thank you

**Comment by altergui** [comment]
thanks for the reminder,
if my findings are correct, then this is a bug upstream.
so i made an issue there
https://github.com/tendermint/tendermint/issues/8077

**Comment by altergui** [comment]
i'll close this issue, although it's not (yet) solved upstream, any further progress will happen there.

**Comment by altergui** [comment]
fixed upstream :partying_face:
