### ISSUE TITLE
bug: race on statedb

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#321]
**Describe the bug**
```
fatal error: concurrent map writes

goroutine 3736 [running]:
runtime.throw({0x28b8f9b, 0x70})
	/usr/lib/go/src/runtime/panic.go:1198 +0x71 fp=0xc0021e0c08 sp=0xc0021e0bd8 pc=0xdd6ed1
runtime.mapassign_faststr(0x2cee300, 0x7fb66c461058, {0x27c90c1, 0x5})
	/usr/lib/go/src/runtime/map_faststr.go:211 +0x39c fp=0xc0021e0c70 sp=0xc0021e0c08 pc=0xdb447c
go.vocdoni.io/dvote/statedb.(*TreeUpdate).SubTree(0xc002385428, {{0xc000f25c80, 0x5, 0x8}, {0x27c90c1, 0x5}, 0xc000063140})
	/home/p4u/repos/vocdoni/go-dvote/statedb/treeupdate.go:159 +0x796 fp=0xc0021e0e18 sp=0xc0021e0c70 pc=0x1a32c16
go.vocdoni.io/dvote/statedb.(*TreeUpdate).DeepSubTree(0x24a1a00, {0xc0031178c0, 0x1, 0x30})
	/home/p4u/repos/vocdoni/go-dvote/statedb/treeupdate.go:168 +0x92 fp=0xc0021e0ea0 sp=0xc0021e0e18 pc=0x1a32dd2
go.vocdoni.io/dvote/statedb.(*TreeUpdate).DeepGet(0x0, {0xc00310fc40, 0x20, 0x20}, {0xc0031178c0, 0x242a7c0, 0xc003142101})
	/home/p4u/repos/vocdoni/go-dvote/statedb/treeupdate.go:178 +0x3a fp=0xc0021e0ee8 sp=0xc0021e0ea0 pc=0x1a32e7a
go.vocdoni.io/dvote/statedb.(*treeUpdateView).DeepGet(0xc0000bced0, {0xc00310fc40, 0xe3, 0xc001eaaf70}, {0xc0031178c0, 0xc000010dd8, 0x24a1ac0})
	/home/p4u/repos/vocdoni/go-dvote/statedb/treeupdate.go:345 +0x25 fp=0xc0021e0f30 sp=0xc0021e0ee8 pc=0x1a33e45
go.vocdoni.io/dvote/vochain.(*State).Process(0xe9b5dba5b5c0fbcf, {0xc00310fc40, 0x20, 0x20}, 0xa4)
	/home/p4u/repos/vocdoni/go-dvote/vochain/process.go:72 +0x22a fp=0xc0021e1030 sp=0xc0021e0f30 pc=0x1a404ca
go.vocdoni.io/dvote/vochain.(*BaseApplication).VoteEnvelopeCheck(0xc000156460, 0xc002ee7550, {0xc0031420f0, 0xe4, 0xf0}, {0xc00314a000, 0x41, 0x50}, {0xcb, 0xef, ...}, ...)
	/home/p4u/repos/vocdoni/go-dvote/vochain/transaction.go:153 +0xbb fp=0xc0021e1300 sp=0xc0021e1030 pc=0x1a4de9b
go.vocdoni.io/dvote/vochain.(*BaseApplication).AddTx(0xc000156460, 0xc003127780, {0xc0031420f0, 0xdaf325, 0x6}, {0xc00314a000, 0xc00008b480, 0xf3e95f}, {0xcb, 0xef, ...}, ...)
	/home/p4u/repos/vocdoni/go-dvote/vochain/transaction.go:33 +0xc38 fp=0xc0021e1400 sp=0xc0021e1300 pc=0x1a4da38
go.vocdoni.io/dvote/vochain.(*BaseApplication).CheckTx(0x4f625c49ca1c96e9, {{0xc002eeba40, 0x0, 0x8}, 0x100a680})
	/home/p4u/repos/vocdoni/go-dvote/vochain/app.go:368 +0x186 fp=0xc0021e1570 sp=0xc0021e1400 pc=0x1a3c7e6
main.main.func1({0xc002eeba40, 0x12a, 0x12c})
	/home/p4u/repos/vocdoni/go-dvote/cmd/singlevochain/singlevochain.go:64 +0x65 fp=0xc0021e16f8 sp=0xc0021e1570 pc=0x22370a5
go.vocdoni.io/dvote/vochain.(*BaseApplication).SendTx(0x241d220, {0xc002eeba40, 0xc00008ba88, 0x2230885})
	/home/p4u/repos/vocdoni/go-dvote/vochain/app.go:250 +0x33 fp=0xc0021e1730 sp=0xc0021e16f8 pc=0x1a3b713
go.vocdoni.io/dvote/router.(*Router).submitRawTx(_, {{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, ...}, ...}, ...})
	/home/p4u/repos/vocdoni/go-dvote/router/voteCallbacks.go:19 +0x55 fp=0xc0021e1a98 sp=0xc0021e1730 pc=0x222f235
go.vocdoni.io/dvote/router.(*Router).submitRawTx-fm({{{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, ...}, ...})
	/home/p4u/repos/vocdoni/go-dvote/router/voteCallbacks.go:18 +0x58 fp=0xc0021e1d40 sp=0xc0021e1a98 pc=0x22341d8
go.vocdoni.io/dvote/router.(*Router).Route·dwrap·4()
	/home/p4u/repos/vocdoni/go-dvote/router/router.go:247 +0x55 fp=0xc0021e1fe0 sp=0xc0021e1d40 pc=0x222e4d5
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc0021e1fe8 sp=0xc0021e1fe0 pc=0xe0b461
created by go.vocdoni.io/dvote/router.(*Router).Route
	/home/p4u/repos/vocdoni/go-dvote/router/router.go:247 +0x552
```

**Comment by p4u** [comment]
fixed by this commit https://github.com/vocdoni/vocdoni-node/pull/322/commits/39e63430bc3c326bac4cfff62cba0b15a0c1593e part of the #322 pull request
