### ISSUE TITLE
Arbo nil pointer (consensus failure)

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#348]
```
2021-11-05T21:12:49Z	INFO	service/census.go:35	[census info] local:30 imported:25 loaded:55 queue:0/10 toRetry:0
2021-11-05T21:12:50Z	INFO	service/vochain.go:205	[vochain info] height:6407 mempool:2 peers:10 processes:197 votes:10611465 vxm:0 voteCache:0 blockTime:{1m:10.00}
2021-11-05T21:12:54Z	WARN	vochain/start.go:130	[tendermint] CONSENSUS FAILURE!!!	{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 64087 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:726 +0x4c\npanic({0x26bd060, 0x40a4480})\n\truntime/panic.go:1038 +0x215\ngithub.com/vocdoni/arbo.(*Tree).AddBatchWithTx(0xc004a6e770, {0x2f3ac10, 0xc01c4693b0}, {0x0, 0xe1b4b4, 0x0}, {0x0, 0x0, 0x0})\n\tgithub.com/vocdoni/arbo@v0.0.0-20210927131431-d7c756341372/tree.go:229 +0x551\ngithub.com/vocdoni/arbo.(*Tree).AddBatch(0xc004a6e770, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0})\n\tgithub.com/vocdoni/arbo@v0.0.0-20210927131431-d7c756341372/tree.go:172 +0x136\ngithub.com/vocdoni/arbo.(*Tree).ImportDump(0xc004a6e770, {0x0, 0x0, 0x0})\n\tgithub.com/vocdoni/arbo@v0.0.0-20210927131431-d7c756341372/tree.go:1093 +0x485\ngo.vocdoni.io/dvote/tree.(*Tree).ImportDump(...)\n\tgo.vocdoni.io/dvote/tree/tree.go:251\ngo.vocdoni.io/dvote/censustree.(*Tree).ImportDump(0xc004218540, {0x0, 0x40, 0xc000000002})\n\tgo.vocdoni.io/dvote/censustree/censustree.go:146 +0xc5\ngo.vocdoni.io/dvote/census.(*Manager).ImportDump(0x20, {0xc0140b5140, 0x40}, 0x2, {0xc01cbaf260, 0x20, 0x20}, {0x0, 0x0, 0x0})\n\tgo.vocdoni.io/dvote/census/importqueue.go:28 +0xeb\ngo.vocdoni.io/dvote/vochain/censusdownloader.(*CensusDownloader).OnProcessesStart(0xc003ecd7c0, {0xc014a70fc0, 0x1, 0x0})\n\tgo.vocdoni.io/dvote/vochain/censusdownloader/censusdownloader.go:107 +0x2d5\ngo.vocdoni.io/dvote/vochain.(*State).Save(0xc003575580)\n\tgo.vocdoni.io/dvote/vochain/state.go:874 +0x1d3\ngo.vocdoni.io/dvote/vochain.(*BaseApplication).Commit(0x5c9a4afa6ad643fe)\n\tgo.vocdoni.io/dvote/vochain/app.go:429 +0x25\ngithub.com/tendermint/tendermint/abci/client.(*localClient).CommitSync(0xc00357f140)\n\tgithub.com/tendermint/tendermint@v0.34.13/abci/client/local_client.go:266 +0xa3\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).CommitSync(0x0)\n\tgithub.com/tendermint/tendermint@v0.34.13/proxy/app_conn.go:93 +0x22\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).Commit(_, {{{0xb, 0x0}, {0xc0029ae1b0, 0x7}}, {0xc003c09290, 0x16}, 0x1, 0x1908, {{0xc01e66f060, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.13/state/execution.go:228 +0x269\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0029ae1b0, 0x7}}, {0xc003c09290, 0x16}, 0x1, 0x1908, {{0xc01e66f060, ...}, ...}, ...}, ...)\n\tgithub.com/tendermint/tendermint@v0.34.13/state/execution.go:180 +0x6ee\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0xc004748700, 0x1908)\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:1635 +0x9fd\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0xc004748700, 0x1908)\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:1546 +0x305\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:1481 +0x87\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0xc004748700, 0x1908, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:1519 +0xc06\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc004748700, 0xc004888140, {0xc0031ed650, 0x28})\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:2132 +0xb6e\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc004748700, 0xc004888140, {0xc0031ed650, 0xc01982fc00})\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:1930 +0x2c\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc004748700, {{0x2ee30c0, 0xc0141f8c68}, {0xc0031ed650, 0x0}})\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:838 +0x40b\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc004748700, 0x0)\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:762 +0x419\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\tgithub.com/tendermint/tendermint@v0.34.13/consensus/state.go:378 +0x12f\n"}
2021-11-05T21:12:57Z	INFO	ipfssync/ipfssync.go:307	[ipfsSync info] pins:851 hash:6348307bc595ecc13af7bfe7bae22b276d6b262103f68d71a666c0d6019ef843
2021-11-05T21:13:09Z	INFO	service/census.go:35	[census info] local:30 imported:26 loaded:56 queue:0/10 toRetry:0
2021-11-05T21:13:10Z	INFO	service/vochain.go:205	[vochain info] height:6408 mempool:2 peers:10 processes:197 votes:10611465 vxm:0 voteCache:0 blockTime:{1m:15.00}
2021-11-05T21:13:17Z	INFO	ipfssync/ipfssync.go:307	[ipfsSync info] pins:851 hash:6348307bc595ecc13af7bfe7bae22b276d6b262103f68d71a666c0d6019ef843
2021-11-05T21:13:19Z	WARN	vochain/start.go:130	[tendermint] dialing failed (attempts: 8): dial tcp 135.181.155.219:26656: connect: connection refused	{"addr": "3e8f9748f437f6ac3b7c4b5090da219e62c9d30b@135.181.155.219:26656"}
2021-11-05T21:13:29Z	INFO	service/census.go:35	[census info] local:30 imported:26 loaded:56 queue:0/10 toRetry:0
2021-11-05T21:13:30Z	INFO	service/vochain.go:205	[vochain info] height:6408 mempool:2 peers:10 processes:197 votes:10611465 vxm:0 voteCache:0 blockTime:{1m:15.00}
```

**Comment by arnaucube** [comment]
Thanks for pasting the logs :raised_hands:
`vocdoni-node` master branch is using `arbo` version from 27th of September, where there is the line of code that appears in the logs that has the 'nil pointer': https://github.com/vocdoni/arbo/blob/d7c7563413728a77be4d9d0e5aa8e4a260dc4b17/tree.go#L229
Since 4th of October, `arbo` was updated with missing checks, which includes one that avoids the error of these logs: https://github.com/vocdoni/arbo/blob/30d8b42fd35707dea5cc4c3360568114c7b84e19/tree.go#L232

Once we update the `arbo` version this error should not happen again
