### ISSUE TITLE
sqlite vs badgerhold inconsistency errors

### ISSUE THREAD

**Issue by p4u** [vocdoni/vocdoni-node#414]
```
2021-12-20T10:24:45Z	DEBUG	scrutinizer/process.go:199	ProcessList badgerhold took 1.674072ms
2021-12-20T10:24:45Z	DEBUG	scrutinizer/process.go:213	ProcessList sqlite took 1.336863ms
  []string{
  	"b1fb3c077cd8e6b97f1fd9da50455c3ce5097a47d99cda870f9221844ef43af9",
- 	"4b23b18d326ac8d7f8ca1a603cc17094c7ecd83c005827c40345284158a82ff8",
- 	"981f43f7ccb528d82eef9ba1d9ff6c6670a460e65ba15961ff25beee057294d5",
  }

params: []interface {}{[]uint8(nil), 0, 64, "", 0x0, "", "", false}
panic: ping mvdan to fix this bug

goroutine 6383142 [running]:
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).ProcessList(0xc0031488c0, {0x0, 0x0, 0x0}, 0x0, 0x40, {0x0, 0x0}, 0x0, {0x0, ...}, ...)
	go.vocdoni.io/dvote/vochain/scrutinizer/process.go:225 +0x2e91
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).getProcessList(0xc0003e2a20, 0xc00c121900)
	go.vocdoni.io/dvote/rpcapi/votehandlers.go:133 +0x118
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).route(0xc0003e2a20, {{0x26f0aa0, 0xc00bef79d0}, {0xc068345b68281de3, 0xd983d3b969, 0x43f5de0}, {0xc0134f2830, 0x1, 0x1}, 0xc0134f27e0})
	go.vocdoni.io/dvote/rpcapi/api.go:109 +0xca
created by go.vocdoni.io/dvote/httprouter.(*HTTProuter).routerHandler.func1
	go.vocdoni.io/dvote/httprouter/httprouter.go:237 +0x3f9
```

**Comment by p4u** [comment]
```
2021-12-20T16:08:46Z	DEBUG	scrutinizer/process.go:199	ProcessList badgerhold took 7.583132ms
2021-12-20T16:08:46Z	DEBUG	scrutinizer/process.go:213	ProcessList sqlite took 1.205918ms
  []string{
  	"b1fb3c077cd8e6b97f1fd9da50455c3ce5097a47d99cda870f9221844ef43af9",
- 	"981f43f7ccb528d82eef9ba1d9ff6c6670a460e65ba15961ff25beee057294d5",
- 	"4b23b18d326ac8d7f8ca1a603cc17094c7ecd83c005827c40345284158a82ff8",
- 	"88e66cdf1cac93ded9c8d13b7cc74601c7f25bf50d392549e1146eaa8429ab01",
- 	"1c0c379164ef4c5ef1b37669c51b22a82a4c988305f1ff1309f84ba8d00a629c",
- 	"dc00b5c8f10fff1255509b501556ec8a0f6939249d73314f60adc1e46493a80e",
- 	"04075deac9317108687ce6111657ecc8cf9428915b8d13092725068ce4edcace",
- 	"2ae3db29e95362a28734682435793392814dd4db7b8cf9dcab65521cd0a3e546",
- 	"e6197e8ed05b0f138fc964d7335d9d275ad59a532adf3f7cce70a9658a1288a3",
- 	"dd2df1aaeb3e40a5d486d58aeadc836f1caa2a59d2f4e601265ec62d48f21ab4",
- 	"937c93cc7250136b3c82d31353176594dbe4879bfd60bbacc32cc309b46da4f4",
  	"8492eda662db37b8d2cf64580f2b00cce3a06a73c3606c272869cc35e888ab61",
  	strings.Join({
- 		"93f56be0ddc69ad566e797dc243639f60c7edf2eb0db5d1cff1315ec012cc989",
+ 		"12163e20c9ad152d3a95c8acaafafb3f6c4a243b428eb23566ddba6eb827d9ee",
  	}, ""),
  	strings.Join({
- 		"12163e20c9ad152d3a95c8acaafafb3f6c4a243b428eb23566ddba6eb827d9ee",
+ 		"93f56be0ddc69ad566e797dc243639f60c7edf2eb0db5d1cff1315ec012cc989",
  	}, ""),
- 	"719cbdfa740f53804c16b64974d256605db2704c0a819e9d2d32aa390c2b123e",
- 	"487b334e7b275f41cd6a19fd893f53183a852408bea38e26bdd3e77acb2763e3",
  	"a7fcbee4da990f2e3f7eaddc168a95aaed18f3fc15c4e596981312a32753d7ad",
+ 	"1dae05f50fedb28ddbd3144779f6fa1b359c429349e6f9c37ce2f249e6dbb9a0",
  	"63061381bb9eb2a328ff3e734117b4e0ce3955d21a81bc01b3787d784c7d0cbc",
- 	"1dae05f50fedb28ddbd3144779f6fa1b359c429349e6f9c37ce2f249e6dbb9a0",
  	... // 19 identical and 6 removed elements
  }

params: []interface {}{[]uint8(nil), 0, 64, "", 0x0, "", "", false}
2021-12-20T16:08:46Z	WARN	scrutinizer/process.go:225	ping mvdan to fix this bug
2021-12-20T16:08:46Z	DEBUG	jsonrpcapi/message.go:60	response: {"response":{"ok":true,"processList":["b1fb3c077cd8e6b97f1fd9da50455c3ce5097a47d99cda870f9221844ef43af9","981f43f7ccb528d82eef9ba1d9ff6c6670a460e65ba15961ff25beee057294d5","4b23b18d326ac8d7f8ca1a603cc17094c7ecd83c005827c40345284158a82ff8","88e66cdf1cac93ded9c8d13b7cc74601c7f25bf50d392549e1146eaa8429ab01","1c0c379164ef4c5ef1b37669c51b22a82a4c988305f1ff1309f84ba8d00a629c","dc00b5c8f10fff1255509b501556ec8a0f6939249d73314f60adc1e46493a80e","04075deac9317108687ce6111657ecc8cf9428915b8d13092725068ce4edcace","2ae3db29e95362a28734682435793392814dd4db7b8cf9dcab65521cd0a3e546","e6197e8ed05b0f138fc964d7335d9d275ad59a532adf3f7cce70a9658a1288a3","dd2df1aaeb3e40a5d486d58aeadc836f1caa2a59d2f4e601265ec62d48f21ab4","937c93cc7250136b3c82d31353176594dbe4879bfd60bbacc32cc309b46da4f4","8492eda662db37b8d2cf64580f2b00cce3a06a73c3606c272869cc35e888ab61","93f56be0ddc69ad566e797dc243639f60c7edf2eb0db5d1cff1315ec012cc989","12163e20c9ad152d3a95c8acaafafb3f6c4a243b428eb23566ddba6eb827d9ee","719cbdfa740f53804c16b64974d256605db2704c0a819e9d2d32aa390c2b123e","487b334e7b275f41cd6a19fd893f53183a852408bea38e26bdd3e77acb2763e3","a7fcbee4da990f2e3f7eaddc168a95aaed18f3fc15c4e596981312a32753d7ad","63061381bb9eb2a328ff3e734117b4e0ce3955d21a81bc01b3787d784c7d0cbc","1dae05f50fedb28ddbd3144779f6fa1b359c429349e6f9c37ce2f249e6dbb9a0","3ccd883036ea5aeb26747137b5fa19c78ce426094658953dd3bd304b45c7bed8","027f11e7ee984df4e3fd93b46edf1be02327b4028c43ad34ee522ac995084461","d8740ee633d968da6332544dfb0ae107cedaa0406daa3e97003593c20662de0e","1ce1882093cb44d36177c4f806fe713dc481ba5fd9bd1ddba9ca05503c128721","c1a3ee73796737095ef34f39301400086d32122ff2cf6221edcf5774e83ecb3b","ea7d87354850e4a739d119fe4d58a4d610a368fd40fd8bc88f876f84a4f30da7","e8ae568ea6807e61996da578275079bff605eb44c581a75686bb66e554dc72fa","91ac4c60b99e865c3b19297e1879bc53bbb96599bb010c43a1755d9274002c2c","a947de17412bca71ff82e1a1053f90a229a76d321a8843a0ddb5308ccd8c0741","d80889a4f86c4cdcd7b04af92e9afc9e9247be6de1deab7d50a1bbf2cc3e6270","6c437686f46af16539cf37c179118b74f77b071f584255fd95b4773401116cf6","c81d96501948c4a54ec50f97aaf0e41f88d3db176435159059d1a4dac59a4e0b","773c0a7b8463438656a988198acc6830907cdee5cdc1a32eb663851113a37669","943c63bd9c3096f2d661e72460f1ded3da678ad917ba847d2d30340abfbbc847","77fedb0358c2c0fae4d759317d3ee3e1d1ff5a265002244b28d444c2dff19e1a","40d83a47df3c88cbe8b1a1e155ce6634694e42b433f906a5503fbc4f0f074e20","f9e2afc5683c2b4c595c22b0841f87b1f835e4c20b10f94b570d44461c46ef00","40e9231b987f9233329907a9f4e5a42691c9d283416ef1c27afff005cbd04baf","626f79d4c269cc57fe31228afa698973afb0055dfd0da0921e361500b2fe48f8","1a098a6551329077bdb6661fb384f8c9c40d8de9055108c5959c9fd79e0e4a17","7b44d1afd06a0025656f09bb674715b0ddf74a89c5549fa27462c01a06163c1e","57a1f0d0140ff6e6622cf1a3858e8b711971abb60e8425c75391befbeac13960","6a070f7b4a9b1752e4e06d8d802d9a723fb1110381c9a72d47e441f649c3dfd5","c6a0206349b6999ad4604f733660d3f364d6486ccf700ad452d85e3e3212d805","63aff6b1c306fac5b42e7826f9a525a17da70cc2c285fd90b0cba8f91cac0928"],"request":"844","size":44,"timestamp":1640016526},"id":"844","signature":"c510f91c1e93fa97be6469ab860ac69e9613adeeb4b15ef7415c5cf4bd876a891cdab4988d0887971cd5a88641f2c4f99898c8397406233ad6117cf91c83032c00"}
```

**Comment by mvdan** [comment]
Should be fixed by https://github.com/vocdoni/vocdoni-node/pull/432, I'm pretty sure. @vdo @p4u please let me know if the latest master still runs into these warnings :)

**Comment by altergui** [comment]
i'm not 100% sure if this is the same bug, but it looks very much related so reopening here for better context.

this test failed right now, on a totally scrutinizer-unrelated branch based on current master
https://github.com/vocdoni/vocdoni-node/runs/4936004408?check_suite_focus=true#step:4:345
```
2022-01-25T11:24:30Z	FATAL	scrutinizer/process.go:43	ping mvdan to fix the bug with the information below:
params: []interface {}{[]uint8{0x0, 0x55, 0x2e, 0x78, 0x7c, 0xe4, 0xe3, 0x8e, 0xe1, 0x28, 0x62, 0x4b, 0xb5, 0x9c, 0x7b, 0x7a, 0xb8, 0xf5, 0xb8, 0xce}, 0, 10, "", 0x0, "", "", false}
diff (-badger +sql):
  []string{
  	strings.Join({
- 		"bded9bffb698d5290344474fa66eef503f108faef9366797cc256285e6f3b002",
+ 		"13c587448efece9b97e636e31af27ff0ad087d1a53597e2904333768202bf357",
  	}, ""),
  	strings.Join({
- 		"f6e8e440fd4d975c5649b29df8e49d6fce90b896779f5fc996b29241fb4cfb9e",
+ 		"c1d793e161343e98a0439291cc15417c976367ea2b904719c215ecc1235b266b",
  	}, ""),
  	strings.Join({
- 		"105b0591fabf0d86f32ea9db7fd944005c20a6962768c53b04c7cb035353a1f0",
+ 		"0cac36d449e350c15ebf519c634151ffd5ed7a5723382139b7cb28ce795b82fb",
  	}, ""),
  	strings.Join({
- 		"229e5cb4f3198df453aa5a79c8c8bdd0be5d615594f49342f55e0b4e239c71cd",
+ 		"8203f1b84bf4667e0f070559f40537228c7fa1bacaccd7cfad553252147cc0f5",
  	}, ""),
  	strings.Join({
- 		"c9d1e8436530ae692fe5dafcd491ad4052d34cf88de85bd0990edc09d77456f9",
+ 		"b788501eec0421c79ddd0ba9e633ede6be499106b35ca737fa629cdc082ba3dd",
  	}, ""),
  	strings.Join({
  		"e",
+ 		"3",
  		"1",
- 		"4cbb3f14631489fe6967b984030b847ed0ba59c84b3163330503af3b98db39",
+ 		"0a849b097e77d9bf2d1b2403076c200d2802b366e4f574cb6574d473127ac",
  	}, ""),
  	strings.Join({
- 		"e6ef487f5365e7dee6b8bce4d4690129f3e749e21673b6e8675ffcd8d6cabe04",
+ 		"f188647613110d7810c2e4027d94e5b63cf90a3d0fb9c69f71af4f8c9eb478b0",
  	}, ""),
  	strings.Join({
- 		"46db7b7744cc94afcceb3659622567d4523693893bceb2b1c19dccdcafbdee8a",
+ 		"8990cfa76834341c3c155b0ae47f3e64be730515054c8f2f0b8c8e36e9618c8e",
  	}, ""),
  	strings.Join({
- 		"6b8b92f5c81bd6497a4e9e71a1ae2f55783e1388142fc069a086438d4f48ca68",
+ 		"989e1b174ce00a84632b3d5b5e5178b5ac0751cdb53d59e3d62b1e806104e43b",
  	}, ""),
  	strings.Join({
- 		"7c2909c9e5ef49b01a69278cf7d7bad35c5b7714892da2514b773a70151247c6",
+ 		"bded9bffb698d5290344474fa66eef503f108faef9366797cc256285e6f3b002",
  	}, ""),
  }

go.vocdoni.io/dvote/vochain/scrutinizer.sqliteWarnf
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:43
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).ProcessList
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:229
go.vocdoni.io/dvote/vochain/scrutinizer.testProcessList
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer_test.go:223
go.vocdoni.io/dvote/vochain/scrutinizer.TestProcessList
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/scrutinizer_test.go:175
testing.tRunner
	/usr/local/go/src/testing/testing.go:1259
FAIL	go.vocdoni.io/dvote/vochain/scrutinizer	14.863s
```

**Comment by mvdan** [comment]
Thanks; looks related to https://github.com/vocdoni/vocdoni-node/pull/419#issuecomment-1020639540.

**Comment by mvdan** [comment]
There's another round of these panics; they all seem to have the same pattern:

```
gw2: 2022-01-25T17:20:46Z	WARN	scrutinizer/process.go:45	ping mvdan to fix the bug with the information below:
gw2: params: []interface {}{[]uint8{0x87, 0xc1, 0x3b, 0x52, 0x16, 0x9d, 0x9d, 0x80, 0x0, 0xfc, 0x6e, 0x2a, 0x20, 0xda, 0xb5, 0x8, 0x8e, 0xc0, 0x93, 0x2b}, 0, 64, "", 0x0, "", "", false}
gw2: diff (-badger +sql):
gw2:   []string{
gw2:   	... // 2 identical elements
gw2:   	"2c4caa2cc401c84f2bb8cc76180ccfa3ab2bc5317075c2795c56cb983f6e0719",
gw2:   	"4afedba2d6593fa3b7019757d2ad354fa5287c9e36fd87be013808fc89fd2bcc",
gw2: - 	"60ef438bec2e807ae0c6a0fa052016f5d2e3f063c7757611792af760e1609de8",
gw2:   }
gw2: 

gw3: 2022-01-25T11:33:41Z	WARN	scrutinizer/process.go:45	ping mvdan to fix the bug with the information below:
gw3: params: []interface {}{[]uint8{0x33, 0x9e, 0x48, 0x3e, 0x21, 0xde, 0xe3, 0x5b, 0x1d, 0x62, 0x7, 0xca, 0x2, 0xbe, 0x2e, 0x1a, 0x3, 0xc, 0x8, 0xa7}, 0, 64, "", 0x0, "", "", false}
gw3: diff (-badger +sql):
gw3:   []string{
gw3: - 	"52f27b670eacb977cd6245ea802760910ee04111a0b31b2b19ed9ca9f1fd7c08",
gw3: - 	"42e1c71b81df0c3a06982d7f517b6feae91f7e1bae2d942f162caf31b33c4756",
gw3: - 	"ac96faaacdb55b617ae451d70e812e752bf954cf9b51a88b5625fc6d37a2f9dc",
gw3: - 	"6bb44018d701bc56a29ab41af8009c58d5daf024dd5d4b3408d01ace852b7d0f",
gw3:   }
```

So it seems like something might be wrong when we filter by entity ID. I'm investigating.

**Comment by mvdan** [comment]
Closing as I believe we've fixed all the warnings in dev again.

**Comment by altergui** [comment]
maybe totally unrelated but posting this here since it says "-badger +sql" and "ping mvdan"
https://github.com/vocdoni/vocdoni-node/actions/runs/3111809114/jobs/5044523330#step:5:468

```
2022-09-23T09:51:00Z	FATAL	scrutinizer/process.go:65	ping mvdan to fix the bug with the information below:
params: c5d2460186f7ea707584ff68516975de899e8311a6780d08df90030000000000
diff (-badger +sql):
  &indexertypes.Results{
  	... // 5 identical fields
  	VoteOpts:    &{MaxCount: 16, MaxValue: 8},
  	Signatures:  nil,
- 	Final:       false,
+ 	Final:       true,
- 	BlockHeight: 0,
+ 	BlockHeight: 23,
  }

go.vocdoni.io/dvote/vochain/scrutinizer.sqliteWarnf
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:65
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).GetResults
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/vote.go:405
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).getResults
	/__w/vocdoni-node/vocdoni-node/rpcapi/votehandlers.go:352
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).route
	/__w/vocdoni-node/vocdoni-node/rpcapi/api.go:109
FAIL	go.vocdoni.io/dvote/vocone	14.883s
FAIL
Error: Process completed with exit code 1.
```

**Comment by altergui** [comment]
another one, same line of code 
https://github.com/vocdoni/vocdoni-node/actions/runs/3130402221/jobs/5080610197#step:5:468
```
2022-09-26T19:17:47Z	FATAL	scrutinizer/process.go:65	ping mvdan to fix the bug with the information below:
params: c5d2460186f785945502c9f455d58ad5941c013c868ddb5c58a2030000000000
diff (-badger +sql):
  &indexertypes.Process{
  	... // 19 identical fields
  	CreationTime:      s"2022-09-26 19:17:42 +0000 UTC",
  	HaveResults:       true,
- 	FinalResults:      false,
+ 	FinalResults:      true,
  	SourceBlockHeight: 0,
  	SourceNetworkId:   "UNKNOWN",
  	... // 2 identical fields
  }

go.vocdoni.io/dvote/vochain/scrutinizer.sqliteWarnf
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:65
go.vocdoni.io/dvote/vochain/scrutinizer.(*Scrutinizer).ProcessInfo
	/__w/vocdoni-node/vocdoni-node/vochain/scrutinizer/process.go:98
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).getResults
	/__w/vocdoni-node/vocdoni-node/rpcapi/votehandlers.go:328
go.vocdoni.io/dvote/rpcapi.(*RPCAPI).route
	/__w/vocdoni-node/vocdoni-node/rpcapi/api.go:109
FAIL	go.vocdoni.io/dvote/vocone	9.635s
FAIL
```

**Comment by mvdan** [comment]
I should have closed this with https://github.com/vocdoni/vocdoni-node/pull/640; see the added comment:

```
	// We only complain when running the tests.
	// In production, the two databases are modified in parallel.
	// For example, when a process is finished, one database is updated
	// immediately after the other.
	// If a client query comes in between those two write operations,
	// the response to the query might see inconsistent results from the DBs.
	// That is fine for production.
	//
	// We still want to catch the inconsistencies while running the tests,
	// because they do help catch SQL schema and query bugs.
	// Tests tend to be sequential with their DBs, so there aren't such races.
```
