### ISSUE TITLE
bug: nil pointer on verify proof offchain CSP

### ISSUE THREAD

**Issue by jordipainan** [vocdoni/vocdoni-node#628]
```
2022-10-10T11:11:09Z	DEBUG	vochain/transaction.go:560	new vote 379eb910c0ff4abda948c2fa43390c37a472e3b78ec4da866ae9821c8cb8630c for address 0x9F4D681E3cBC6f858A24e14EdA09F17a54bC7ad6 and process 24ba45c1dfaa4a081070e9d555b5d19629a6bcc8b77f4ae6d39c03000000001c
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x2b57358]

goroutine 234740198 [running]:
go.vocdoni.io/dvote/vochain.VerifyProofOffChainCSP(0xcd?, 0xc00c5a1780, 0x3?, {0xc0177a25c0, 0x40, 0x40}, {0xc019283720, 0x20, 0x20}, {0xc00585a3f0, ...}, ...)
	go.vocdoni.io/dvote/vochain/proof.go:114 +0xb8
go.vocdoni.io/dvote/vochain.VerifyProof(0xc00b308591?, 0xc0041972b8?, 0x118ae54?, {0xc004197320?, 0x16f01d3?, 0xc00b308591?}, {0x1?, 0xf?, 0x0?}, {0xc00585a3f0, ...}, ...)
	go.vocdoni.io/dvote/vochain/proof.go:55 +0xd2
go.vocdoni.io/dvote/vochain.(*BaseApplication).VoteEnvelopeCheck(0xc0051f8210, 0xc0148e4c60, {0xc017bbba80, 0x73, 0x73}, {0xc01b337590, 0x41, 0x50}, {0xa3, 0x51, ...}, ...)
	go.vocdoni.io/dvote/vochain/transaction.go:562 +0x10f4
```

Reported on gw1 dev

**Comment by jordipainan** [comment]
**Process**:

```
"process": {
      "censusOrigin": 3,
      "censusRoot": "66316432383236376466613564646363643935626136366236663631616161323438336633343632363561636438656137363439333331353334623535613533",
      "censusURI": "ipfs://QmPHBbuacksngmujUnrPsxvhw44QP2NfkC1kmPuWURfCoA",
      "creationTime": "2022-10-10T10:57:43Z",
      "endBlock": 253966,
      "entityId": "34613038313037306539643535356235643139363239613662636338623737663461653664333963",
      "entityIndex": 0,
      "envelopeType": {},
      "finalResults": false,
      "haveResults": true,
      "maxCensusSize": 0,
      "metadata": "ipfs://QmQmLXCUcZf4J6b818t6nvszoVyDWouARqh6h6aaDYo9PR",
      "namespace": 0,
      "processId": "24ba45c1dfaa4a081070e9d555b5d19629a6bcc8b77f4ae6d39c03000000001c",
      "processMode": {
        "autoStart": true,
        "interruptible": true
      },
      "questionIndex": 0,
      "rollingCensusRoot": "",
      "rollingCensusSize": 0,
      "sourceBlockHeight": 0,
      "sourceNetworkId": "UNKNOWN",
      "startBlock": 253166,
      "status": 1,
      "voteOptions": {
        "costExponent": 10000,
        "maxCount": 2,
        "maxValue": 2,
        "maxVoteOverwrites": 1
      }
    },
```

**Comment by jordipainan** [comment]
1. transaction.go#345 acknowledges that Process is not NIL
2. transaction.go#528 acknowledges that vote.Proof is not NIL
3. transaction.go#562 executes a VerifyProof() and halts at proof.go#114
```golang
if !bytes.Equal(p.Bundle.Address, key) {
		return false, nil, fmt.Errorf(
			"CSP bundle address and key do not match: %x != %x", key, p.Bundle.Address)
}
```
So probably `p.Bundle` is nil

**Comment by jordipainan** [comment]
relates #630
